// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: golden_srv.proto

package com.kys.pb;

public final class GoldenSrv {
  private GoldenSrv() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S_GetRoomInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb_golden.S_GetRoomInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    java.util.List<GoldenProto.RoomInfo>
        getRoomsList();
    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    GoldenProto.RoomInfo getRooms(int index);
    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    int getRoomsCount();
    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    java.util.List<? extends GoldenProto.RoomInfoOrBuilder>
        getRoomsOrBuilderList();
    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    GoldenProto.RoomInfoOrBuilder getRoomsOrBuilder(
        int index);
  }
  /**
   * <pre>
   ** 服务器返回房间列表信息 
   * </pre>
   *
   * Protobuf type {@code pb_golden.S_GetRoomInfo}
   */
  public  static final class S_GetRoomInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb_golden.S_GetRoomInfo)
      S_GetRoomInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S_GetRoomInfo.newBuilder() to construct.
    private S_GetRoomInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S_GetRoomInfo() {
      rooms_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new S_GetRoomInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S_GetRoomInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                rooms_ = new java.util.ArrayList<GoldenProto.RoomInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              rooms_.add(
                  input.readMessage(GoldenProto.RoomInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          rooms_ = java.util.Collections.unmodifiableList(rooms_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GoldenSrv.internal_static_pb_golden_S_GetRoomInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GoldenSrv.internal_static_pb_golden_S_GetRoomInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              S_GetRoomInfo.class, Builder.class);
    }

    public static final int ROOMS_FIELD_NUMBER = 1;
    private java.util.List<GoldenProto.RoomInfo> rooms_;
    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    public java.util.List<GoldenProto.RoomInfo> getRoomsList() {
      return rooms_;
    }
    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    public java.util.List<? extends GoldenProto.RoomInfoOrBuilder>
        getRoomsOrBuilderList() {
      return rooms_;
    }
    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    public int getRoomsCount() {
      return rooms_.size();
    }
    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    public GoldenProto.RoomInfo getRooms(int index) {
      return rooms_.get(index);
    }
    /**
     * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
     */
    public GoldenProto.RoomInfoOrBuilder getRoomsOrBuilder(
        int index) {
      return rooms_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < rooms_.size(); i++) {
        output.writeMessage(1, rooms_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rooms_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rooms_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof S_GetRoomInfo)) {
        return super.equals(obj);
      }
      S_GetRoomInfo other = (S_GetRoomInfo) obj;

      if (!getRoomsList()
          .equals(other.getRoomsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRoomsCount() > 0) {
        hash = (37 * hash) + ROOMS_FIELD_NUMBER;
        hash = (53 * hash) + getRoomsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static S_GetRoomInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_GetRoomInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_GetRoomInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_GetRoomInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_GetRoomInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_GetRoomInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_GetRoomInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S_GetRoomInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static S_GetRoomInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static S_GetRoomInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static S_GetRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S_GetRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(S_GetRoomInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 服务器返回房间列表信息 
     * </pre>
     *
     * Protobuf type {@code pb_golden.S_GetRoomInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb_golden.S_GetRoomInfo)
        S_GetRoomInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GoldenSrv.internal_static_pb_golden_S_GetRoomInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GoldenSrv.internal_static_pb_golden_S_GetRoomInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                S_GetRoomInfo.class, Builder.class);
      }

      // Construct using com.kys.pb.GoldenSrv.S_GetRoomInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRoomsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (roomsBuilder_ == null) {
          rooms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          roomsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GoldenSrv.internal_static_pb_golden_S_GetRoomInfo_descriptor;
      }

      @Override
      public S_GetRoomInfo getDefaultInstanceForType() {
        return S_GetRoomInfo.getDefaultInstance();
      }

      @Override
      public S_GetRoomInfo build() {
        S_GetRoomInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public S_GetRoomInfo buildPartial() {
        S_GetRoomInfo result = new S_GetRoomInfo(this);
        int from_bitField0_ = bitField0_;
        if (roomsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            rooms_ = java.util.Collections.unmodifiableList(rooms_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rooms_ = rooms_;
        } else {
          result.rooms_ = roomsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof S_GetRoomInfo) {
          return mergeFrom((S_GetRoomInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(S_GetRoomInfo other) {
        if (other == S_GetRoomInfo.getDefaultInstance()) return this;
        if (roomsBuilder_ == null) {
          if (!other.rooms_.isEmpty()) {
            if (rooms_.isEmpty()) {
              rooms_ = other.rooms_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRoomsIsMutable();
              rooms_.addAll(other.rooms_);
            }
            onChanged();
          }
        } else {
          if (!other.rooms_.isEmpty()) {
            if (roomsBuilder_.isEmpty()) {
              roomsBuilder_.dispose();
              roomsBuilder_ = null;
              rooms_ = other.rooms_;
              bitField0_ = (bitField0_ & ~0x00000001);
              roomsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRoomsFieldBuilder() : null;
            } else {
              roomsBuilder_.addAllMessages(other.rooms_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        S_GetRoomInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (S_GetRoomInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<GoldenProto.RoomInfo> rooms_ =
        java.util.Collections.emptyList();
      private void ensureRoomsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          rooms_ = new java.util.ArrayList<GoldenProto.RoomInfo>(rooms_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GoldenProto.RoomInfo, GoldenProto.RoomInfo.Builder, GoldenProto.RoomInfoOrBuilder> roomsBuilder_;

      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public java.util.List<GoldenProto.RoomInfo> getRoomsList() {
        if (roomsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rooms_);
        } else {
          return roomsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public int getRoomsCount() {
        if (roomsBuilder_ == null) {
          return rooms_.size();
        } else {
          return roomsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public GoldenProto.RoomInfo getRooms(int index) {
        if (roomsBuilder_ == null) {
          return rooms_.get(index);
        } else {
          return roomsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public Builder setRooms(
          int index, GoldenProto.RoomInfo value) {
        if (roomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomsIsMutable();
          rooms_.set(index, value);
          onChanged();
        } else {
          roomsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public Builder setRooms(
          int index, GoldenProto.RoomInfo.Builder builderForValue) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.set(index, builderForValue.build());
          onChanged();
        } else {
          roomsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public Builder addRooms(GoldenProto.RoomInfo value) {
        if (roomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomsIsMutable();
          rooms_.add(value);
          onChanged();
        } else {
          roomsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public Builder addRooms(
          int index, GoldenProto.RoomInfo value) {
        if (roomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomsIsMutable();
          rooms_.add(index, value);
          onChanged();
        } else {
          roomsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public Builder addRooms(
          GoldenProto.RoomInfo.Builder builderForValue) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.add(builderForValue.build());
          onChanged();
        } else {
          roomsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public Builder addRooms(
          int index, GoldenProto.RoomInfo.Builder builderForValue) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.add(index, builderForValue.build());
          onChanged();
        } else {
          roomsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public Builder addAllRooms(
          Iterable<? extends GoldenProto.RoomInfo> values) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rooms_);
          onChanged();
        } else {
          roomsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public Builder clearRooms() {
        if (roomsBuilder_ == null) {
          rooms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          roomsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public Builder removeRooms(int index) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.remove(index);
          onChanged();
        } else {
          roomsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public GoldenProto.RoomInfo.Builder getRoomsBuilder(
          int index) {
        return getRoomsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public GoldenProto.RoomInfoOrBuilder getRoomsOrBuilder(
          int index) {
        if (roomsBuilder_ == null) {
          return rooms_.get(index);  } else {
          return roomsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public java.util.List<? extends GoldenProto.RoomInfoOrBuilder>
           getRoomsOrBuilderList() {
        if (roomsBuilder_ != null) {
          return roomsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rooms_);
        }
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public GoldenProto.RoomInfo.Builder addRoomsBuilder() {
        return getRoomsFieldBuilder().addBuilder(
            GoldenProto.RoomInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public GoldenProto.RoomInfo.Builder addRoomsBuilder(
          int index) {
        return getRoomsFieldBuilder().addBuilder(
            index, GoldenProto.RoomInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .pb_golden.RoomInfo rooms = 1;</code>
       */
      public java.util.List<GoldenProto.RoomInfo.Builder>
           getRoomsBuilderList() {
        return getRoomsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GoldenProto.RoomInfo, GoldenProto.RoomInfo.Builder, GoldenProto.RoomInfoOrBuilder>
          getRoomsFieldBuilder() {
        if (roomsBuilder_ == null) {
          roomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GoldenProto.RoomInfo, GoldenProto.RoomInfo.Builder, GoldenProto.RoomInfoOrBuilder>(
                  rooms_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          rooms_ = null;
        }
        return roomsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb_golden.S_GetRoomInfo)
    }

    // @@protoc_insertion_point(class_scope:pb_golden.S_GetRoomInfo)
    private static final S_GetRoomInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new S_GetRoomInfo();
    }

    public static S_GetRoomInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S_GetRoomInfo>
        PARSER = new com.google.protobuf.AbstractParser<S_GetRoomInfo>() {
      @Override
      public S_GetRoomInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S_GetRoomInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S_GetRoomInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<S_GetRoomInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public S_GetRoomInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S_JoinRoomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb_golden.S_JoinRoom)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 桌子对象 
     * </pre>
     *
     * <code>.pb_golden.TableInfo table = 1;</code>
     */
    boolean hasTable();
    /**
     * <pre>
     ** 桌子对象 
     * </pre>
     *
     * <code>.pb_golden.TableInfo table = 1;</code>
     */
    GoldenProto.TableInfo getTable();
    /**
     * <pre>
     ** 桌子对象 
     * </pre>
     *
     * <code>.pb_golden.TableInfo table = 1;</code>
     */
    GoldenProto.TableInfoOrBuilder getTableOrBuilder();

    /**
     * <pre>
     ** 是否是恢复状态 
     * </pre>
     *
     * <code>bool isRecover = 2;</code>
     */
    boolean getIsRecover();
  }
  /**
   * <pre>
   ** 服务器返回加入房间后的桌子信息 
   * </pre>
   *
   * Protobuf type {@code pb_golden.S_JoinRoom}
   */
  public  static final class S_JoinRoom extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb_golden.S_JoinRoom)
      S_JoinRoomOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S_JoinRoom.newBuilder() to construct.
    private S_JoinRoom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S_JoinRoom() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new S_JoinRoom();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S_JoinRoom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              GoldenProto.TableInfo.Builder subBuilder = null;
              if (table_ != null) {
                subBuilder = table_.toBuilder();
              }
              table_ = input.readMessage(GoldenProto.TableInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(table_);
                table_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              isRecover_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GoldenSrv.internal_static_pb_golden_S_JoinRoom_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GoldenSrv.internal_static_pb_golden_S_JoinRoom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              S_JoinRoom.class, Builder.class);
    }

    public static final int TABLE_FIELD_NUMBER = 1;
    private GoldenProto.TableInfo table_;
    /**
     * <pre>
     ** 桌子对象 
     * </pre>
     *
     * <code>.pb_golden.TableInfo table = 1;</code>
     */
    public boolean hasTable() {
      return table_ != null;
    }
    /**
     * <pre>
     ** 桌子对象 
     * </pre>
     *
     * <code>.pb_golden.TableInfo table = 1;</code>
     */
    public GoldenProto.TableInfo getTable() {
      return table_ == null ? GoldenProto.TableInfo.getDefaultInstance() : table_;
    }
    /**
     * <pre>
     ** 桌子对象 
     * </pre>
     *
     * <code>.pb_golden.TableInfo table = 1;</code>
     */
    public GoldenProto.TableInfoOrBuilder getTableOrBuilder() {
      return getTable();
    }

    public static final int ISRECOVER_FIELD_NUMBER = 2;
    private boolean isRecover_;
    /**
     * <pre>
     ** 是否是恢复状态 
     * </pre>
     *
     * <code>bool isRecover = 2;</code>
     */
    public boolean getIsRecover() {
      return isRecover_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (table_ != null) {
        output.writeMessage(1, getTable());
      }
      if (isRecover_ != false) {
        output.writeBool(2, isRecover_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (table_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTable());
      }
      if (isRecover_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isRecover_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof S_JoinRoom)) {
        return super.equals(obj);
      }
      S_JoinRoom other = (S_JoinRoom) obj;

      if (hasTable() != other.hasTable()) return false;
      if (hasTable()) {
        if (!getTable()
            .equals(other.getTable())) return false;
      }
      if (getIsRecover()
          != other.getIsRecover()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTable()) {
        hash = (37 * hash) + TABLE_FIELD_NUMBER;
        hash = (53 * hash) + getTable().hashCode();
      }
      hash = (37 * hash) + ISRECOVER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsRecover());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static S_JoinRoom parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_JoinRoom parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_JoinRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_JoinRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_JoinRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_JoinRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_JoinRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S_JoinRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static S_JoinRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static S_JoinRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static S_JoinRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S_JoinRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(S_JoinRoom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 服务器返回加入房间后的桌子信息 
     * </pre>
     *
     * Protobuf type {@code pb_golden.S_JoinRoom}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb_golden.S_JoinRoom)
        S_JoinRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GoldenSrv.internal_static_pb_golden_S_JoinRoom_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GoldenSrv.internal_static_pb_golden_S_JoinRoom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                S_JoinRoom.class, Builder.class);
      }

      // Construct using com.kys.pb.GoldenSrv.S_JoinRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (tableBuilder_ == null) {
          table_ = null;
        } else {
          table_ = null;
          tableBuilder_ = null;
        }
        isRecover_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GoldenSrv.internal_static_pb_golden_S_JoinRoom_descriptor;
      }

      @Override
      public S_JoinRoom getDefaultInstanceForType() {
        return S_JoinRoom.getDefaultInstance();
      }

      @Override
      public S_JoinRoom build() {
        S_JoinRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public S_JoinRoom buildPartial() {
        S_JoinRoom result = new S_JoinRoom(this);
        if (tableBuilder_ == null) {
          result.table_ = table_;
        } else {
          result.table_ = tableBuilder_.build();
        }
        result.isRecover_ = isRecover_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof S_JoinRoom) {
          return mergeFrom((S_JoinRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(S_JoinRoom other) {
        if (other == S_JoinRoom.getDefaultInstance()) return this;
        if (other.hasTable()) {
          mergeTable(other.getTable());
        }
        if (other.getIsRecover() != false) {
          setIsRecover(other.getIsRecover());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        S_JoinRoom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (S_JoinRoom) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private GoldenProto.TableInfo table_;
      private com.google.protobuf.SingleFieldBuilderV3<
          GoldenProto.TableInfo, GoldenProto.TableInfo.Builder, GoldenProto.TableInfoOrBuilder> tableBuilder_;
      /**
       * <pre>
       ** 桌子对象 
       * </pre>
       *
       * <code>.pb_golden.TableInfo table = 1;</code>
       */
      public boolean hasTable() {
        return tableBuilder_ != null || table_ != null;
      }
      /**
       * <pre>
       ** 桌子对象 
       * </pre>
       *
       * <code>.pb_golden.TableInfo table = 1;</code>
       */
      public GoldenProto.TableInfo getTable() {
        if (tableBuilder_ == null) {
          return table_ == null ? GoldenProto.TableInfo.getDefaultInstance() : table_;
        } else {
          return tableBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       ** 桌子对象 
       * </pre>
       *
       * <code>.pb_golden.TableInfo table = 1;</code>
       */
      public Builder setTable(GoldenProto.TableInfo value) {
        if (tableBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          table_ = value;
          onChanged();
        } else {
          tableBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 桌子对象 
       * </pre>
       *
       * <code>.pb_golden.TableInfo table = 1;</code>
       */
      public Builder setTable(
          GoldenProto.TableInfo.Builder builderForValue) {
        if (tableBuilder_ == null) {
          table_ = builderForValue.build();
          onChanged();
        } else {
          tableBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       ** 桌子对象 
       * </pre>
       *
       * <code>.pb_golden.TableInfo table = 1;</code>
       */
      public Builder mergeTable(GoldenProto.TableInfo value) {
        if (tableBuilder_ == null) {
          if (table_ != null) {
            table_ =
              GoldenProto.TableInfo.newBuilder(table_).mergeFrom(value).buildPartial();
          } else {
            table_ = value;
          }
          onChanged();
        } else {
          tableBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       ** 桌子对象 
       * </pre>
       *
       * <code>.pb_golden.TableInfo table = 1;</code>
       */
      public Builder clearTable() {
        if (tableBuilder_ == null) {
          table_ = null;
          onChanged();
        } else {
          table_ = null;
          tableBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       ** 桌子对象 
       * </pre>
       *
       * <code>.pb_golden.TableInfo table = 1;</code>
       */
      public GoldenProto.TableInfo.Builder getTableBuilder() {
        
        onChanged();
        return getTableFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       ** 桌子对象 
       * </pre>
       *
       * <code>.pb_golden.TableInfo table = 1;</code>
       */
      public GoldenProto.TableInfoOrBuilder getTableOrBuilder() {
        if (tableBuilder_ != null) {
          return tableBuilder_.getMessageOrBuilder();
        } else {
          return table_ == null ?
              GoldenProto.TableInfo.getDefaultInstance() : table_;
        }
      }
      /**
       * <pre>
       ** 桌子对象 
       * </pre>
       *
       * <code>.pb_golden.TableInfo table = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GoldenProto.TableInfo, GoldenProto.TableInfo.Builder, GoldenProto.TableInfoOrBuilder>
          getTableFieldBuilder() {
        if (tableBuilder_ == null) {
          tableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GoldenProto.TableInfo, GoldenProto.TableInfo.Builder, GoldenProto.TableInfoOrBuilder>(
                  getTable(),
                  getParentForChildren(),
                  isClean());
          table_ = null;
        }
        return tableBuilder_;
      }

      private boolean isRecover_ ;
      /**
       * <pre>
       ** 是否是恢复状态 
       * </pre>
       *
       * <code>bool isRecover = 2;</code>
       */
      public boolean getIsRecover() {
        return isRecover_;
      }
      /**
       * <pre>
       ** 是否是恢复状态 
       * </pre>
       *
       * <code>bool isRecover = 2;</code>
       */
      public Builder setIsRecover(boolean value) {
        
        isRecover_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 是否是恢复状态 
       * </pre>
       *
       * <code>bool isRecover = 2;</code>
       */
      public Builder clearIsRecover() {
        
        isRecover_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb_golden.S_JoinRoom)
    }

    // @@protoc_insertion_point(class_scope:pb_golden.S_JoinRoom)
    private static final S_JoinRoom DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new S_JoinRoom();
    }

    public static S_JoinRoom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S_JoinRoom>
        PARSER = new com.google.protobuf.AbstractParser<S_JoinRoom>() {
      @Override
      public S_JoinRoom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S_JoinRoom(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S_JoinRoom> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<S_JoinRoom> getParserForType() {
      return PARSER;
    }

    @Override
    public S_JoinRoom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S_ExitRoomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb_golden.S_ExitRoom)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   ** 服务端返回离开桌子 
   * </pre>
   *
   * Protobuf type {@code pb_golden.S_ExitRoom}
   */
  public  static final class S_ExitRoom extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb_golden.S_ExitRoom)
      S_ExitRoomOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S_ExitRoom.newBuilder() to construct.
    private S_ExitRoom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S_ExitRoom() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new S_ExitRoom();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S_ExitRoom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GoldenSrv.internal_static_pb_golden_S_ExitRoom_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GoldenSrv.internal_static_pb_golden_S_ExitRoom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              S_ExitRoom.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof S_ExitRoom)) {
        return super.equals(obj);
      }
      S_ExitRoom other = (S_ExitRoom) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static S_ExitRoom parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_ExitRoom parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_ExitRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_ExitRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_ExitRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_ExitRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_ExitRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S_ExitRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static S_ExitRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static S_ExitRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static S_ExitRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S_ExitRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(S_ExitRoom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 服务端返回离开桌子 
     * </pre>
     *
     * Protobuf type {@code pb_golden.S_ExitRoom}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb_golden.S_ExitRoom)
        S_ExitRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GoldenSrv.internal_static_pb_golden_S_ExitRoom_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GoldenSrv.internal_static_pb_golden_S_ExitRoom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                S_ExitRoom.class, Builder.class);
      }

      // Construct using com.kys.pb.GoldenSrv.S_ExitRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GoldenSrv.internal_static_pb_golden_S_ExitRoom_descriptor;
      }

      @Override
      public S_ExitRoom getDefaultInstanceForType() {
        return S_ExitRoom.getDefaultInstance();
      }

      @Override
      public S_ExitRoom build() {
        S_ExitRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public S_ExitRoom buildPartial() {
        S_ExitRoom result = new S_ExitRoom(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof S_ExitRoom) {
          return mergeFrom((S_ExitRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(S_ExitRoom other) {
        if (other == S_ExitRoom.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        S_ExitRoom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (S_ExitRoom) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb_golden.S_ExitRoom)
    }

    // @@protoc_insertion_point(class_scope:pb_golden.S_ExitRoom)
    private static final S_ExitRoom DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new S_ExitRoom();
    }

    public static S_ExitRoom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S_ExitRoom>
        PARSER = new com.google.protobuf.AbstractParser<S_ExitRoom>() {
      @Override
      public S_ExitRoom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S_ExitRoom(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S_ExitRoom> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<S_ExitRoom> getParserForType() {
      return PARSER;
    }

    @Override
    public S_ExitRoom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S_BetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb_golden.S_Bet)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   ** 服务端返回表态 
   * </pre>
   *
   * Protobuf type {@code pb_golden.S_Bet}
   */
  public  static final class S_Bet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb_golden.S_Bet)
      S_BetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S_Bet.newBuilder() to construct.
    private S_Bet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S_Bet() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new S_Bet();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S_Bet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GoldenSrv.internal_static_pb_golden_S_Bet_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GoldenSrv.internal_static_pb_golden_S_Bet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              S_Bet.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof S_Bet)) {
        return super.equals(obj);
      }
      S_Bet other = (S_Bet) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static S_Bet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_Bet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_Bet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_Bet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_Bet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static S_Bet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static S_Bet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S_Bet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static S_Bet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static S_Bet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static S_Bet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static S_Bet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(S_Bet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 服务端返回表态 
     * </pre>
     *
     * Protobuf type {@code pb_golden.S_Bet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb_golden.S_Bet)
        S_BetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GoldenSrv.internal_static_pb_golden_S_Bet_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GoldenSrv.internal_static_pb_golden_S_Bet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                S_Bet.class, Builder.class);
      }

      // Construct using com.kys.pb.GoldenSrv.S_Bet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GoldenSrv.internal_static_pb_golden_S_Bet_descriptor;
      }

      @Override
      public S_Bet getDefaultInstanceForType() {
        return S_Bet.getDefaultInstance();
      }

      @Override
      public S_Bet build() {
        S_Bet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public S_Bet buildPartial() {
        S_Bet result = new S_Bet(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof S_Bet) {
          return mergeFrom((S_Bet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(S_Bet other) {
        if (other == S_Bet.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        S_Bet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (S_Bet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb_golden.S_Bet)
    }

    // @@protoc_insertion_point(class_scope:pb_golden.S_Bet)
    private static final S_Bet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new S_Bet();
    }

    public static S_Bet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S_Bet>
        PARSER = new com.google.protobuf.AbstractParser<S_Bet>() {
      @Override
      public S_Bet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S_Bet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S_Bet> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<S_Bet> getParserForType() {
      return PARSER;
    }

    @Override
    public S_Bet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_golden_S_GetRoomInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_golden_S_GetRoomInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_golden_S_JoinRoom_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_golden_S_JoinRoom_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_golden_S_ExitRoom_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_golden_S_ExitRoom_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_golden_S_Bet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_golden_S_Bet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020golden_srv.proto\022\tpb_golden\032\014golden.pr" +
      "oto\"3\n\rS_GetRoomInfo\022\"\n\005rooms\030\001 \003(\0132\023.pb" +
      "_golden.RoomInfo\"D\n\nS_JoinRoom\022#\n\005table\030" +
      "\001 \001(\0132\024.pb_golden.TableInfo\022\021\n\tisRecover" +
      "\030\002 \001(\010\"\014\n\nS_ExitRoom\"\007\n\005S_BetB\027\n\ncom.kys" +
      ".pbB\tGoldenSrvb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GoldenProto.getDescriptor(),
        });
    internal_static_pb_golden_S_GetRoomInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_golden_S_GetRoomInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_golden_S_GetRoomInfo_descriptor,
        new String[] { "Rooms", });
    internal_static_pb_golden_S_JoinRoom_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_golden_S_JoinRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_golden_S_JoinRoom_descriptor,
        new String[] { "Table", "IsRecover", });
    internal_static_pb_golden_S_ExitRoom_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_golden_S_ExitRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_golden_S_ExitRoom_descriptor,
        new String[] { });
    internal_static_pb_golden_S_Bet_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pb_golden_S_Bet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_golden_S_Bet_descriptor,
        new String[] { });
    GoldenProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
