// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_result.proto

package com.kys.pb;

public final class PbCode {
  private PbCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   ** 服务器返回码 
   * </pre>
   *
   * Protobuf enum {@code pb.ResultCode}
   */
  public enum ResultCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     ** 成功 
     * </pre>
     *
     * <code>success = 0;</code>
     */
    success(0),
    /**
     * <pre>
     ** 任意失败 
     * </pre>
     *
     * <code>err = 1;</code>
     */
    err(1),
    /**
     * <pre>
     ** 没有该方法错误 
     * </pre>
     *
     * <code>errNoMethod = 2;</code>
     */
    errNoMethod(2),
    /**
     * <pre>
     ** 消息为空 
     * </pre>
     *
     * <code>errNulMsg = 3;</code>
     */
    errNulMsg(3),
    /**
     * <pre>
     ** 登录过期 
     * </pre>
     *
     * <code>errLoginInvalid = 4;</code>
     */
    errLoginInvalid(4),
    /**
     * <pre>
     ** 网络连接错误 
     * </pre>
     *
     * <code>errNetConnect = 5;</code>
     */
    errNetConnect(5),
    /**
     * <pre>
     ** 请先完成游戏 
     * </pre>
     *
     * <code>errGameNotOver = 6;</code>
     */
    errGameNotOver(6),
    /**
     * <pre>
     ** 登陆错误 
     * </pre>
     *
     * <code>errLogin = 100;</code>
     */
    errLogin(100),
    /**
     * <pre>
     ** token失效 
     * </pre>
     *
     * <code>errLoginTokenInvalid = 101;</code>
     */
    errLoginTokenInvalid(101),
    /**
     * <pre>
     ** 账号违规，无法登录 
     * </pre>
     *
     * <code>errLoginBan = 102;</code>
     */
    errLoginBan(102),
    /**
     * <pre>
     ** 重连时间过期 
     * </pre>
     *
     * <code>errLoginReconnect = 103;</code>
     */
    errLoginReconnect(103),
    /**
     * <pre>
     ** 排行榜错误 
     * </pre>
     *
     * <code>errRank = 300;</code>
     */
    errRank(300),
    /**
     * <pre>
     ** 排行榜为空 
     * </pre>
     *
     * <code>errRankEmpty = 301;</code>
     */
    errRankEmpty(301),
    /**
     * <pre>
     ** 抽奖失败，未知错误 
     * </pre>
     *
     * <code>errLottery = 400;</code>
     */
    errLottery(400),
    /**
     * <pre>
     ** 抽奖失败，剩余次数不足 
     * </pre>
     *
     * <code>errLotteryNotEnough = 401;</code>
     */
    errLotteryNotEnough(401),
    /**
     * <pre>
     ** 商城错误 
     * </pre>
     *
     * <code>errShop = 500;</code>
     */
    errShop(500),
    /**
     * <pre>
     ** 物品不存在 
     * </pre>
     *
     * <code>errShopItemNotExist = 501;</code>
     */
    errShopItemNotExist(501),
    /**
     * <pre>
     ** 购买货币不足 
     * </pre>
     *
     * <code>errShopChipNotEnough = 502;</code>
     */
    errShopChipNotEnough(502),
    /**
     * <pre>
     ** 每日礼包今天已经购买完：今天已经购买完了,请明天再来 
     * </pre>
     *
     * <code>errDailyGiftNoLeft = 503;</code>
     */
    errDailyGiftNoLeft(503),
    /**
     * <pre>
     ** 金豆复活礼包已经买完 
     * </pre>
     *
     * <code>errGoldcoinResGiftNoLeft = 504;</code>
     */
    errGoldcoinResGiftNoLeft(504),
    /**
     * <pre>
     ** 钻石复活礼包已经买完 
     * </pre>
     *
     * <code>errDiamondResGiftNoLeft = 505;</code>
     */
    errDiamondResGiftNoLeft(505),
    /**
     * <pre>
     ** 当天购买次数已用尽 
     * </pre>
     *
     * <code>errUnmatchBuyResGift = 506;</code>
     */
    errUnmatchBuyResGift(506),
    /**
     * <pre>
     ** 未关注公众号 
     * </pre>
     *
     * <code>errNotFollowWxAccount = 507;</code>
     */
    errNotFollowWxAccount(507),
    /**
     * <pre>
     ** 兑换失败 
     * </pre>
     *
     * <code>errConvertFailed = 508;</code>
     */
    errConvertFailed(508),
    /**
     * <pre>
     ** 未绑定手机号 
     * </pre>
     *
     * <code>errNotBindTel = 509;</code>
     */
    errNotBindTel(509),
    /**
     * <pre>
     ** 企业付款到限额:今日红包已发完，请明日尽早领取 
     * </pre>
     *
     * <code>errEnPayNoMoney = 510;</code>
     */
    errEnPayNoMoney(510),
    /**
     * <pre>
     ** 微信红包没有钱了,兑换失败，请联系客服 
     * </pre>
     *
     * <code>errWxRedNoMoney = 511;</code>
     */
    errWxRedNoMoney(511),
    /**
     * <pre>
     ** 今日充值超限 
     * </pre>
     *
     * <code>errChargeOver = 512;</code>
     */
    errChargeOver(512),
    /**
     * <pre>
     ** 微信系统繁忙 
     * </pre>
     *
     * <code>errWxSystemError = 513;</code>
     */
    errWxSystemError(513),
    /**
     * <pre>
     ** 抽奖等待时间未到 
     * </pre>
     *
     * <code>errLotteryWaitTime = 514;</code>
     */
    errLotteryWaitTime(514),
    /**
     * <pre>
     ** 本周兑换次数已经用尽 
     * </pre>
     *
     * <code>errExchangeExhaust = 515;</code>
     */
    errExchangeExhaust(515),
    /**
     * <pre>
     ** 兑换话费,京东卡金额超限 
     * </pre>
     *
     * <code>errChargeOrJdCard = 516;</code>
     */
    errChargeOrJdCard(516),
    /**
     * <pre>
     ** 加入房间错误码 
     * </pre>
     *
     * <code>errRoom = 600;</code>
     */
    errRoom(600),
    /**
     * <pre>
     ** 筹码不足加入房间 
     * </pre>
     *
     * <code>errRoomChipNotEnough = 601;</code>
     */
    errRoomChipNotEnough(601),
    /**
     * <pre>
     ** 钻石不足加入房间 
     * </pre>
     *
     * <code>errRoomDiamondNotEnough = 602;</code>
     */
    errRoomDiamondNotEnough(602),
    /**
     * <pre>
     ** 重新加入房间错误，房间不存在
     * </pre>
     *
     * <code>errRoomNotExist = 603;</code>
     */
    errRoomNotExist(603),
    /**
     * <pre>
     ** 玩家不在房间中 
     * </pre>
     *
     * <code>errRoomNotIn = 604;</code>
     */
    errRoomNotIn(604),
    /**
     * <pre>
     ** 筹码大于加入房间最大值 
     * </pre>
     *
     * <code>errRoomChipToMuch = 605;</code>
     */
    errRoomChipToMuch(605),
    /**
     * <pre>
     ** 钻石大于加入房间最大值 
     * </pre>
     *
     * <code>errRoomDiamondToMuch = 606;</code>
     */
    errRoomDiamondToMuch(606),
    /**
     * <pre>
     ** 因为报名比赛,不能加入游戏 
     * </pre>
     *
     * <code>errRoomInMatch = 607;</code>
     */
    errRoomInMatch(607),
    /**
     * <pre>
     ** 用户信息接口 
     * </pre>
     *
     * <code>errUserIsNull = 701;</code>
     */
    errUserIsNull(701),
    /**
     * <pre>
     ** 游戏接口 
     * </pre>
     *
     * <code>errGame = 800;</code>
     */
    errGame(800),
    /**
     * <pre>
     ** 房间不存在 
     * </pre>
     *
     * <code>errGameRoomNotExist = 801;</code>
     */
    errGameRoomNotExist(801),
    /**
     * <pre>
     ** 当前房间不在游戏中，不能托管 
     * </pre>
     *
     * <code>errGameAutoPlay = 802;</code>
     */
    errGameAutoPlay(802),
    /**
     * <pre>
     ** 当前不应该该玩家操作 
     * </pre>
     *
     * <code>errGameInvaildOper = 803;</code>
     */
    errGameInvaildOper(803),
    /**
     * <pre>
     ** 叫地主分值非法 
     * </pre>
     *
     * <code>errGameInvaildCatchPoint = 804;</code>
     */
    errGameInvaildCatchPoint(804),
    /**
     * <pre>
     ** 进入房间失败 
     * </pre>
     *
     * <code>errGameEnterRoomFail = 805;</code>
     */
    errGameEnterRoomFail(805),
    /**
     * <pre>
     ** 玩家不在房间中 
     * </pre>
     *
     * <code>errGamePlayerNotIn = 806;</code>
     */
    errGamePlayerNotIn(806),
    /**
     * <pre>
     ** 玩家牌型错误 
     * </pre>
     *
     * <code>errGameCardInvaild = 807;</code>
     */
    errGameCardInvaild(807),
    /**
     * <pre>
     ** 互动表情时间未到 
     * </pre>
     *
     * <code>errGameSendActionTime = 808;</code>
     */
    errGameSendActionTime(808),
    /**
     * <pre>
     ** 分享接口
     * </pre>
     *
     * <code>errPm = 900;</code>
     */
    errPm(900),
    /**
     * <pre>
     ** 分享接口-发送短信校验码-手机号码非法
     * </pre>
     *
     * <code>errPmTelNumInvaild = 901;</code>
     */
    errPmTelNumInvaild(901),
    /**
     * <pre>
     ** 发送短信校验码-验证码校验失败
     * </pre>
     *
     * <code>errPmVerifyCodeFail = 902;</code>
     */
    errPmVerifyCodeFail(902),
    /**
     * <pre>
     ** 领取分享奖励失败-未完成 
     * </pre>
     *
     * <code>errPmGetAwardNotFinish = 903;</code>
     */
    errPmGetAwardNotFinish(903),
    /**
     * <pre>
     ** 领取分享奖励失败-未绑定手机号
     * </pre>
     *
     * <code>errPmGetAwardNotBindTel = 904;</code>
     */
    errPmGetAwardNotBindTel(904),
    /**
     * <pre>
     ** 已经绑定过手机号了 
     * </pre>
     *
     * <code>errPmAlreadyBind = 905;</code>
     */
    errPmAlreadyBind(905),
    /**
     * <pre>
     ** 重发验证码时间过短
     * </pre>
     *
     * <code>errPmRequestIntervalTooShort = 906;</code>
     */
    errPmRequestIntervalTooShort(906),
    /**
     * <pre>
     ** 分包失败 
     * </pre>
     *
     * <code>errPmSharePackageFail = 907;</code>
     */
    errPmSharePackageFail(907),
    /**
     * <pre>
     ** 还没有任何小伙伴接受邀请 
     * </pre>
     *
     * <code>errPmNoSlave = 908;</code>
     */
    errPmNoSlave(908),
    /**
     * <pre>
     ** 你和请求玩家不是小伙伴
     * </pre>
     *
     * <code>errPmNotRelationship = 909;</code>
     */
    errPmNotRelationship(909),
    /**
     * <pre>
     ** 手机号已经被绑定了 
     * </pre>
     *
     * <code>errPmTelAlreadyUsed = 910;</code>
     */
    errPmTelAlreadyUsed(910),
    /**
     * <pre>
     ** 推送奖励公告为空 
     * </pre>
     *
     * <code>errAwardMsgIsNul = 1000;</code>
     */
    errAwardMsgIsNul(1000),
    /**
     * <pre>
     ** 领取失败 
     * </pre>
     *
     * <code>errGetDailyFailed = 1100;</code>
     */
    errGetDailyFailed(1100),
    /**
     * <pre>
     ** 新手任务已过期 
     * </pre>
     *
     * <code>errNoviceTaskexpired = 1200;</code>
     */
    errNoviceTaskexpired(1200),
    /**
     * <pre>
     ** 领取失败 
     * </pre>
     *
     * <code>errGetNoviceFailed = 1201;</code>
     */
    errGetNoviceFailed(1201),
    /**
     * <pre>
     ** 删除失败，请先领取 
     * </pre>
     *
     * <code>errDeleteMail = 1300;</code>
     */
    errDeleteMail(1300),
    /**
     * <pre>
     ** 夺宝商城接口错误 
     * </pre>
     *
     * <code>errSnatch = 1400;</code>
     */
    errSnatch(1400),
    /**
     * <pre>
     ** 获取夺宝商城主界面报错 
     * </pre>
     *
     * <code>errSnatchGetList = 1401;</code>
     */
    errSnatchGetList(1401),
    /**
     * <pre>
     ** 夺宝-下注值超过能下注值 
     * </pre>
     *
     * <code>errSnatchInvaildBet = 1402;</code>
     */
    errSnatchInvaildBet(1402),
    /**
     * <pre>
     ** 夺宝-红包不足下注 
     * </pre>
     *
     * <code>errSnatchWincupNotEnough = 1403;</code>
     */
    errSnatchWincupNotEnough(1403),
    /**
     * <pre>
     ** 夺宝-不能领取奖励 
     * </pre>
     *
     * <code>errSnatchInvaildGetAward = 1404;</code>
     */
    errSnatchInvaildGetAward(1404),
    /**
     * <pre>
     ** 夺宝-已经没有更多的历史记录了
     * </pre>
     *
     * <code>errSnatchNoMoreHistories = 1405;</code>
     */
    errSnatchNoMoreHistories(1405),
    /**
     * <pre>
     ** 夺宝-没有填写详细的地址信息，不能领取实物奖励 
     * </pre>
     *
     * <code>errSnatchRequireAddrDetail = 1406;</code>
     */
    errSnatchRequireAddrDetail(1406),
    /**
     * <pre>
     ** 夺宝投入最少为100 
     * </pre>
     *
     * <code>errSnatchRequire = 1407;</code>
     */
    errSnatchRequire(1407),
    /**
     * <pre>
     ** 钻石宝箱接口错误 
     * </pre>
     *
     * <code>errDG = 1500;</code>
     */
    errDG(1500),
    /**
     * <pre>
     **钻石宝箱已经过期 
     * </pre>
     *
     * <code>errDGExpired = 1501;</code>
     */
    errDGExpired(1501),
    /**
     * <pre>
     ** 宝箱已经抽取完了,请重置 
     * </pre>
     *
     * <code>errBoxIsOver = 1502;</code>
     */
    errBoxIsOver(1502),
    /**
     * <pre>
     ** 重置失败 
     * </pre>
     *
     * <code>errReset = 1503;</code>
     */
    errReset(1503),
    /**
     * <pre>
     ** 游戏开启失败 
     * </pre>
     *
     * <code>errOpenDg = 1504;</code>
     */
    errOpenDg(1504),
    /**
     * <pre>
     ** 可重置没有重置机会 
     * </pre>
     *
     * <code>errNoLeftCont = 1505;</code>
     */
    errNoLeftCont(1505),
    /**
     * <pre>
     ** 重置机会用完了 
     * </pre>
     *
     * <code>errNoChance = 1506;</code>
     */
    errNoChance(1506),
    /**
     * <pre>
     ** 道具背包接口报错
     * </pre>
     *
     * <code>errProp = 1600;</code>
     */
    errProp(1600),
    /**
     * <pre>
     ** 没有这个道具报错
     * </pre>
     *
     * <code>errPropNotHaveThisProp = 1601;</code>
     */
    errPropNotHaveThisProp(1601),
    /**
     * <pre>
     ** 不满足道具使用条件 
     * </pre>
     *
     * <code>errNotMatchUseCondition = 1602;</code>
     */
    errNotMatchUseCondition(1602),
    /**
     * <pre>
     ** 签到接口错误 
     * </pre>
     *
     * <code>errSign = 1700;</code>
     */
    errSign(1700),
    /**
     * <pre>
     ** 重复签到 
     * </pre>
     *
     * <code>errSignRepeate = 1701;</code>
     */
    errSignRepeate(1701),
    /**
     * <pre>
     ** 补签卡不足 
     * </pre>
     *
     * <code>errSignRSCNotEnough = 1702;</code>
     */
    errSignRSCNotEnough(1702),
    /**
     * <pre>
     ** 钻石不足 
     * </pre>
     *
     * <code>errSignRSDNotEnough = 1703;</code>
     */
    errSignRSDNotEnough(1703),
    /**
     * <pre>
     ** 签到时间错误 
     * </pre>
     *
     * <code>errSignTime = 1704;</code>
     */
    errSignTime(1704),
    /**
     * <pre>
     ** 幸运时钟抽奖失败 
     * </pre>
     *
     * <code>errSignLT = 1705;</code>
     */
    errSignLT(1705),
    /**
     * <pre>
     ** vip等级不足 
     * </pre>
     *
     * <code>errSignVipLack = 1706;</code>
     */
    errSignVipLack(1706),
    /**
     * <pre>
     ** 奖励已领取 
     * </pre>
     *
     * <code>errSignRewardHasGet = 1707;</code>
     */
    errSignRewardHasGet(1707),
    /**
     * <pre>
     ** 签到时间不足 
     * </pre>
     *
     * <code>errSignDayNotEnough = 1708;</code>
     */
    errSignDayNotEnough(1708),
    /**
     * <pre>
     ** VIP接口错误 
     * </pre>
     *
     * <code>errVipLvNotEnough = 1801;</code>
     */
    errVipLvNotEnough(1801),
    /**
     * <pre>
     ** 本周已经领过每周奖励了 
     * </pre>
     *
     * <code>errVipWeekAwardAlreadyGet = 1802;</code>
     */
    errVipWeekAwardAlreadyGet(1802),
    /**
     * <pre>
     ** 已经领过每日礼包了 
     * </pre>
     *
     * <code>errVipAlreadyGetDayGift = 1803;</code>
     */
    errVipAlreadyGetDayGift(1803),
    /**
     * <pre>
     ** 因为昨天没抽奖，所以没有领取每日礼包的资格 
     * </pre>
     *
     * <code>errVipNotLottery = 1804;</code>
     */
    errVipNotLottery(1804),
    /**
     * <pre>
     ** 钻石滚动抽奖接口错误 
     * </pre>
     *
     * <code>errDD = 1900;</code>
     */
    errDD(1900),
    /**
     * <pre>
     ** 钻石不足 
     * </pre>
     *
     * <code>errDNotEnough = 1901;</code>
     */
    errDNotEnough(1901),
    /**
     * <pre>
     ** 该活动已关闭 
     * </pre>
     *
     * <code>errDDClose = 1902;</code>
     */
    errDDClose(1902),
    /**
     * <pre>
     ** 剩余次数不足 
     * </pre>
     *
     * <code>errDTimesNotEnough = 1903;</code>
     */
    errDTimesNotEnough(1903),
    /**
     * <pre>
     ** 拥有的钻石超过复活限制 
     * </pre>
     *
     * <code>errReviveExceedLimit = 2001;</code>
     */
    errReviveExceedLimit(2001),
    /**
     * <pre>
     ** 玩家复活次数不足 
     * </pre>
     *
     * <code>errReviveNotEnough = 2002;</code>
     */
    errReviveNotEnough(2002),
    /**
     * <pre>
     ** 拥有的金币超过复活限制 
     * </pre>
     *
     * <code>errReviveGoldLimit = 2003;</code>
     */
    errReviveGoldLimit(2003),
    /**
     * <pre>
     ** 该局比赛报名已经结束 
     * </pre>
     *
     * <code>errMatchApplyOver = 2101;</code>
     */
    errMatchApplyOver(2101),
    /**
     * <pre>
     ** 报名卡不足 
     * </pre>
     *
     * <code>errMatchApplyCardNotEnough = 2102;</code>
     */
    errMatchApplyCardNotEnough(2102),
    /**
     * <pre>
     ** 取消报名失败 
     * </pre>
     *
     * <code>errMatchCancelFail = 2103;</code>
     */
    errMatchCancelFail(2103),
    /**
     * <pre>
     ** 报名至少需要50钻石 
     * </pre>
     *
     * <code>errMatchEnterLimitDiamond = 2104;</code>
     */
    errMatchEnterLimitDiamond(2104),
    /**
     * <pre>
     ** 报名至少需要100金豆 
     * </pre>
     *
     * <code>errMatchEnterLimitGold = 2105;</code>
     */
    errMatchEnterLimitGold(2105),
    /**
     * <pre>
     ** 该局比赛已经结束 
     * </pre>
     *
     * <code>errMatchAlreadyOver = 2106;</code>
     */
    errMatchAlreadyOver(2106),
    /**
     * <pre>
     ** 你已经在其他比赛中了 
     * </pre>
     *
     * <code>errAlreadyInMatch = 2107;</code>
     */
    errAlreadyInMatch(2107),
    /**
     * <pre>
     ** 实名认证报错 
     * </pre>
     *
     * <code>errIdVerify = 2201;</code>
     */
    errIdVerify(2201),
    /**
     * <pre>
     ** 身份证格式不正确 
     * </pre>
     *
     * <code>errIdVerifyFormat = 2202;</code>
     */
    errIdVerifyFormat(2202),
    /**
     * <pre>
     ** 已经认证成功 
     * </pre>
     *
     * <code>errRepeateIdVerify = 2203;</code>
     */
    errRepeateIdVerify(2203),
    /**
     * <pre>
     ** 金豆不足 
     * </pre>
     *
     * <code>errGoldNotEnough = 2301;</code>
     */
    errGoldNotEnough(2301),
    /**
     * <pre>
     ** 钻石不足 
     * </pre>
     *
     * <code>errDiamondNotEnough = 2302;</code>
     */
    errDiamondNotEnough(2302),
    /**
     * <pre>
     ** 今日游戏次数已经用完了 
     * </pre>
     *
     * <code>errPlayTimesOver = 2303;</code>
     */
    errPlayTimesOver(2303),
    /**
     * <pre>
     ** 钥匙不够 
     * </pre>
     *
     * <code>errKeyNotEnough = 2304;</code>
     */
    errKeyNotEnough(2304),
    /**
     * <pre>
     ** cdkey兑换失败 
     * </pre>
     *
     * <code>errCdkeyFaild = 2401;</code>
     */
    errCdkeyFaild(2401),
    /**
     * <pre>
     ** cdkey兑换码不存在 
     * </pre>
     *
     * <code>errCdkeyErr = 2402;</code>
     */
    errCdkeyErr(2402),
    /**
     * <pre>
     ** cdkey兑换码已过期 
     * </pre>
     *
     * <code>errCdkeyExpired = 2403;</code>
     */
    errCdkeyExpired(2403),
    /**
     * <pre>
     ** cdkey兑换码已领取 
     * </pre>
     *
     * <code>errCdkeyReceived = 2404;</code>
     */
    errCdkeyReceived(2404),
    /**
     * <pre>
     ** cdkey兑换码已领完 
     * </pre>
     *
     * <code>errCdkeyGetOver = 2405;</code>
     */
    errCdkeyGetOver(2405),
    /**
     * <pre>
     ** 财神红包错误码 
     * </pre>
     *
     * <code>errGodLight = 2500;</code>
     */
    errGodLight(2500),
    /**
     * <pre>
     ** 不是红包活动参与者 
     * </pre>
     *
     * <code>errGodLightNotJoiner = 2501;</code>
     */
    errGodLightNotJoiner(2501),
    /**
     * <pre>
     ** 活动尚未开始 
     * </pre>
     *
     * <code>errGodLightActiveNotOpen = 2502;</code>
     */
    errGodLightActiveNotOpen(2502),
    /**
     * <pre>
     ** 玩家所在房间不在活动范围 
     * </pre>
     *
     * <code>errGodLightRoomNotAllow = 2503;</code>
     */
    errGodLightRoomNotAllow(2503),
    /**
     * <pre>
     ** 本轮发奖已经结束了 
     * </pre>
     *
     * <code>errGodLightNotAward = 2504;</code>
     */
    errGodLightNotAward(2504),
    /**
     * <pre>
     ** 本轮已经领过了 
     * </pre>
     *
     * <code>errGodLightAlreadyAwardThisTurn = 2505;</code>
     */
    errGodLightAlreadyAwardThisTurn(2505),
    /**
     * <pre>
     ** 手慢了，红包已经抢完了，下次加油 
     * </pre>
     *
     * <code>errGodFightNextTime = 2506;</code>
     */
    errGodFightNextTime(2506),
    /**
     * <pre>
     ** 古尔邦节活动错误码 
     * </pre>
     *
     * <code>errCorban = 2600;</code>
     */
    errCorban(2600),
    /**
     * <pre>
     ** 该奖励今日已经领取 
     * </pre>
     *
     * <code>errCorbanRepeateGet = 2601;</code>
     */
    errCorbanRepeateGet(2601),
    /**
     * <pre>
     ** 请在活动时间领取 
     * </pre>
     *
     * <code>errCorbanNotStart = 2602;</code>
     */
    errCorbanNotStart(2602),
    /**
     * <pre>
     ** 当前时间段只能领取一次 
     * </pre>
     *
     * <code>errThisTimeGetOnce = 2603;</code>
     */
    errThisTimeGetOnce(2603),
    /**
     * <pre>
     ** 奖励已领取 
     * </pre>
     *
     * <code>errRankShareAwardHasGet = 2701;</code>
     */
    errRankShareAwardHasGet(2701),
    /**
     * <pre>
     ** 成就奖励领取错误 
     * </pre>
     *
     * <code>errGetAchievementAward = 2801;</code>
     */
    errGetAchievementAward(2801),
    /**
     * <pre>
     ** 活动已过期 
     * </pre>
     *
     * <code>errActivityExpire = 2901;</code>
     */
    errActivityExpire(2901),
    /**
     * <pre>
     ** 实物商城领取次数超限 
     * </pre>
     *
     * <code>errPhysicalStoreLimit = 2902;</code>
     */
    errPhysicalStoreLimit(2902),
    /**
     * <pre>
     ** 活动积分不足 
     * </pre>
     *
     * <code>errScoreNotEnough = 3001;</code>
     */
    errScoreNotEnough(3001),
    /**
     * <pre>
     ** 请在第7天来领取 
     * </pre>
     *
     * <code>errAdvanceReceive = 3002;</code>
     */
    errAdvanceReceive(3002),
    /**
     * <pre>
     ** 兑换次数超限 
     * </pre>
     *
     * <code>errConvertLimit = 3003;</code>
     */
    errConvertLimit(3003),
    /**
     * <pre>
     ** 奖励已经领取 
     * </pre>
     *
     * <code>errHaveGetAward = 3004;</code>
     */
    errHaveGetAward(3004),
    /**
     * <pre>
     ** 拉取数字已达上限 
     * </pre>
     *
     * <code>errPullMax = 3005;</code>
     */
    errPullMax(3005),
    /**
     * <pre>
     ** 玩家进入场次货币不足 
     * </pre>
     *
     * <code>errGoldenNotEnough = 3101;</code>
     */
    errGoldenNotEnough(3101),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     ** 成功 
     * </pre>
     *
     * <code>success = 0;</code>
     */
    public static final int success_VALUE = 0;
    /**
     * <pre>
     ** 任意失败 
     * </pre>
     *
     * <code>err = 1;</code>
     */
    public static final int err_VALUE = 1;
    /**
     * <pre>
     ** 没有该方法错误 
     * </pre>
     *
     * <code>errNoMethod = 2;</code>
     */
    public static final int errNoMethod_VALUE = 2;
    /**
     * <pre>
     ** 消息为空 
     * </pre>
     *
     * <code>errNulMsg = 3;</code>
     */
    public static final int errNulMsg_VALUE = 3;
    /**
     * <pre>
     ** 登录过期 
     * </pre>
     *
     * <code>errLoginInvalid = 4;</code>
     */
    public static final int errLoginInvalid_VALUE = 4;
    /**
     * <pre>
     ** 网络连接错误 
     * </pre>
     *
     * <code>errNetConnect = 5;</code>
     */
    public static final int errNetConnect_VALUE = 5;
    /**
     * <pre>
     ** 请先完成游戏 
     * </pre>
     *
     * <code>errGameNotOver = 6;</code>
     */
    public static final int errGameNotOver_VALUE = 6;
    /**
     * <pre>
     ** 登陆错误 
     * </pre>
     *
     * <code>errLogin = 100;</code>
     */
    public static final int errLogin_VALUE = 100;
    /**
     * <pre>
     ** token失效 
     * </pre>
     *
     * <code>errLoginTokenInvalid = 101;</code>
     */
    public static final int errLoginTokenInvalid_VALUE = 101;
    /**
     * <pre>
     ** 账号违规，无法登录 
     * </pre>
     *
     * <code>errLoginBan = 102;</code>
     */
    public static final int errLoginBan_VALUE = 102;
    /**
     * <pre>
     ** 重连时间过期 
     * </pre>
     *
     * <code>errLoginReconnect = 103;</code>
     */
    public static final int errLoginReconnect_VALUE = 103;
    /**
     * <pre>
     ** 排行榜错误 
     * </pre>
     *
     * <code>errRank = 300;</code>
     */
    public static final int errRank_VALUE = 300;
    /**
     * <pre>
     ** 排行榜为空 
     * </pre>
     *
     * <code>errRankEmpty = 301;</code>
     */
    public static final int errRankEmpty_VALUE = 301;
    /**
     * <pre>
     ** 抽奖失败，未知错误 
     * </pre>
     *
     * <code>errLottery = 400;</code>
     */
    public static final int errLottery_VALUE = 400;
    /**
     * <pre>
     ** 抽奖失败，剩余次数不足 
     * </pre>
     *
     * <code>errLotteryNotEnough = 401;</code>
     */
    public static final int errLotteryNotEnough_VALUE = 401;
    /**
     * <pre>
     ** 商城错误 
     * </pre>
     *
     * <code>errShop = 500;</code>
     */
    public static final int errShop_VALUE = 500;
    /**
     * <pre>
     ** 物品不存在 
     * </pre>
     *
     * <code>errShopItemNotExist = 501;</code>
     */
    public static final int errShopItemNotExist_VALUE = 501;
    /**
     * <pre>
     ** 购买货币不足 
     * </pre>
     *
     * <code>errShopChipNotEnough = 502;</code>
     */
    public static final int errShopChipNotEnough_VALUE = 502;
    /**
     * <pre>
     ** 每日礼包今天已经购买完：今天已经购买完了,请明天再来 
     * </pre>
     *
     * <code>errDailyGiftNoLeft = 503;</code>
     */
    public static final int errDailyGiftNoLeft_VALUE = 503;
    /**
     * <pre>
     ** 金豆复活礼包已经买完 
     * </pre>
     *
     * <code>errGoldcoinResGiftNoLeft = 504;</code>
     */
    public static final int errGoldcoinResGiftNoLeft_VALUE = 504;
    /**
     * <pre>
     ** 钻石复活礼包已经买完 
     * </pre>
     *
     * <code>errDiamondResGiftNoLeft = 505;</code>
     */
    public static final int errDiamondResGiftNoLeft_VALUE = 505;
    /**
     * <pre>
     ** 当天购买次数已用尽 
     * </pre>
     *
     * <code>errUnmatchBuyResGift = 506;</code>
     */
    public static final int errUnmatchBuyResGift_VALUE = 506;
    /**
     * <pre>
     ** 未关注公众号 
     * </pre>
     *
     * <code>errNotFollowWxAccount = 507;</code>
     */
    public static final int errNotFollowWxAccount_VALUE = 507;
    /**
     * <pre>
     ** 兑换失败 
     * </pre>
     *
     * <code>errConvertFailed = 508;</code>
     */
    public static final int errConvertFailed_VALUE = 508;
    /**
     * <pre>
     ** 未绑定手机号 
     * </pre>
     *
     * <code>errNotBindTel = 509;</code>
     */
    public static final int errNotBindTel_VALUE = 509;
    /**
     * <pre>
     ** 企业付款到限额:今日红包已发完，请明日尽早领取 
     * </pre>
     *
     * <code>errEnPayNoMoney = 510;</code>
     */
    public static final int errEnPayNoMoney_VALUE = 510;
    /**
     * <pre>
     ** 微信红包没有钱了,兑换失败，请联系客服 
     * </pre>
     *
     * <code>errWxRedNoMoney = 511;</code>
     */
    public static final int errWxRedNoMoney_VALUE = 511;
    /**
     * <pre>
     ** 今日充值超限 
     * </pre>
     *
     * <code>errChargeOver = 512;</code>
     */
    public static final int errChargeOver_VALUE = 512;
    /**
     * <pre>
     ** 微信系统繁忙 
     * </pre>
     *
     * <code>errWxSystemError = 513;</code>
     */
    public static final int errWxSystemError_VALUE = 513;
    /**
     * <pre>
     ** 抽奖等待时间未到 
     * </pre>
     *
     * <code>errLotteryWaitTime = 514;</code>
     */
    public static final int errLotteryWaitTime_VALUE = 514;
    /**
     * <pre>
     ** 本周兑换次数已经用尽 
     * </pre>
     *
     * <code>errExchangeExhaust = 515;</code>
     */
    public static final int errExchangeExhaust_VALUE = 515;
    /**
     * <pre>
     ** 兑换话费,京东卡金额超限 
     * </pre>
     *
     * <code>errChargeOrJdCard = 516;</code>
     */
    public static final int errChargeOrJdCard_VALUE = 516;
    /**
     * <pre>
     ** 加入房间错误码 
     * </pre>
     *
     * <code>errRoom = 600;</code>
     */
    public static final int errRoom_VALUE = 600;
    /**
     * <pre>
     ** 筹码不足加入房间 
     * </pre>
     *
     * <code>errRoomChipNotEnough = 601;</code>
     */
    public static final int errRoomChipNotEnough_VALUE = 601;
    /**
     * <pre>
     ** 钻石不足加入房间 
     * </pre>
     *
     * <code>errRoomDiamondNotEnough = 602;</code>
     */
    public static final int errRoomDiamondNotEnough_VALUE = 602;
    /**
     * <pre>
     ** 重新加入房间错误，房间不存在
     * </pre>
     *
     * <code>errRoomNotExist = 603;</code>
     */
    public static final int errRoomNotExist_VALUE = 603;
    /**
     * <pre>
     ** 玩家不在房间中 
     * </pre>
     *
     * <code>errRoomNotIn = 604;</code>
     */
    public static final int errRoomNotIn_VALUE = 604;
    /**
     * <pre>
     ** 筹码大于加入房间最大值 
     * </pre>
     *
     * <code>errRoomChipToMuch = 605;</code>
     */
    public static final int errRoomChipToMuch_VALUE = 605;
    /**
     * <pre>
     ** 钻石大于加入房间最大值 
     * </pre>
     *
     * <code>errRoomDiamondToMuch = 606;</code>
     */
    public static final int errRoomDiamondToMuch_VALUE = 606;
    /**
     * <pre>
     ** 因为报名比赛,不能加入游戏 
     * </pre>
     *
     * <code>errRoomInMatch = 607;</code>
     */
    public static final int errRoomInMatch_VALUE = 607;
    /**
     * <pre>
     ** 用户信息接口 
     * </pre>
     *
     * <code>errUserIsNull = 701;</code>
     */
    public static final int errUserIsNull_VALUE = 701;
    /**
     * <pre>
     ** 游戏接口 
     * </pre>
     *
     * <code>errGame = 800;</code>
     */
    public static final int errGame_VALUE = 800;
    /**
     * <pre>
     ** 房间不存在 
     * </pre>
     *
     * <code>errGameRoomNotExist = 801;</code>
     */
    public static final int errGameRoomNotExist_VALUE = 801;
    /**
     * <pre>
     ** 当前房间不在游戏中，不能托管 
     * </pre>
     *
     * <code>errGameAutoPlay = 802;</code>
     */
    public static final int errGameAutoPlay_VALUE = 802;
    /**
     * <pre>
     ** 当前不应该该玩家操作 
     * </pre>
     *
     * <code>errGameInvaildOper = 803;</code>
     */
    public static final int errGameInvaildOper_VALUE = 803;
    /**
     * <pre>
     ** 叫地主分值非法 
     * </pre>
     *
     * <code>errGameInvaildCatchPoint = 804;</code>
     */
    public static final int errGameInvaildCatchPoint_VALUE = 804;
    /**
     * <pre>
     ** 进入房间失败 
     * </pre>
     *
     * <code>errGameEnterRoomFail = 805;</code>
     */
    public static final int errGameEnterRoomFail_VALUE = 805;
    /**
     * <pre>
     ** 玩家不在房间中 
     * </pre>
     *
     * <code>errGamePlayerNotIn = 806;</code>
     */
    public static final int errGamePlayerNotIn_VALUE = 806;
    /**
     * <pre>
     ** 玩家牌型错误 
     * </pre>
     *
     * <code>errGameCardInvaild = 807;</code>
     */
    public static final int errGameCardInvaild_VALUE = 807;
    /**
     * <pre>
     ** 互动表情时间未到 
     * </pre>
     *
     * <code>errGameSendActionTime = 808;</code>
     */
    public static final int errGameSendActionTime_VALUE = 808;
    /**
     * <pre>
     ** 分享接口
     * </pre>
     *
     * <code>errPm = 900;</code>
     */
    public static final int errPm_VALUE = 900;
    /**
     * <pre>
     ** 分享接口-发送短信校验码-手机号码非法
     * </pre>
     *
     * <code>errPmTelNumInvaild = 901;</code>
     */
    public static final int errPmTelNumInvaild_VALUE = 901;
    /**
     * <pre>
     ** 发送短信校验码-验证码校验失败
     * </pre>
     *
     * <code>errPmVerifyCodeFail = 902;</code>
     */
    public static final int errPmVerifyCodeFail_VALUE = 902;
    /**
     * <pre>
     ** 领取分享奖励失败-未完成 
     * </pre>
     *
     * <code>errPmGetAwardNotFinish = 903;</code>
     */
    public static final int errPmGetAwardNotFinish_VALUE = 903;
    /**
     * <pre>
     ** 领取分享奖励失败-未绑定手机号
     * </pre>
     *
     * <code>errPmGetAwardNotBindTel = 904;</code>
     */
    public static final int errPmGetAwardNotBindTel_VALUE = 904;
    /**
     * <pre>
     ** 已经绑定过手机号了 
     * </pre>
     *
     * <code>errPmAlreadyBind = 905;</code>
     */
    public static final int errPmAlreadyBind_VALUE = 905;
    /**
     * <pre>
     ** 重发验证码时间过短
     * </pre>
     *
     * <code>errPmRequestIntervalTooShort = 906;</code>
     */
    public static final int errPmRequestIntervalTooShort_VALUE = 906;
    /**
     * <pre>
     ** 分包失败 
     * </pre>
     *
     * <code>errPmSharePackageFail = 907;</code>
     */
    public static final int errPmSharePackageFail_VALUE = 907;
    /**
     * <pre>
     ** 还没有任何小伙伴接受邀请 
     * </pre>
     *
     * <code>errPmNoSlave = 908;</code>
     */
    public static final int errPmNoSlave_VALUE = 908;
    /**
     * <pre>
     ** 你和请求玩家不是小伙伴
     * </pre>
     *
     * <code>errPmNotRelationship = 909;</code>
     */
    public static final int errPmNotRelationship_VALUE = 909;
    /**
     * <pre>
     ** 手机号已经被绑定了 
     * </pre>
     *
     * <code>errPmTelAlreadyUsed = 910;</code>
     */
    public static final int errPmTelAlreadyUsed_VALUE = 910;
    /**
     * <pre>
     ** 推送奖励公告为空 
     * </pre>
     *
     * <code>errAwardMsgIsNul = 1000;</code>
     */
    public static final int errAwardMsgIsNul_VALUE = 1000;
    /**
     * <pre>
     ** 领取失败 
     * </pre>
     *
     * <code>errGetDailyFailed = 1100;</code>
     */
    public static final int errGetDailyFailed_VALUE = 1100;
    /**
     * <pre>
     ** 新手任务已过期 
     * </pre>
     *
     * <code>errNoviceTaskexpired = 1200;</code>
     */
    public static final int errNoviceTaskexpired_VALUE = 1200;
    /**
     * <pre>
     ** 领取失败 
     * </pre>
     *
     * <code>errGetNoviceFailed = 1201;</code>
     */
    public static final int errGetNoviceFailed_VALUE = 1201;
    /**
     * <pre>
     ** 删除失败，请先领取 
     * </pre>
     *
     * <code>errDeleteMail = 1300;</code>
     */
    public static final int errDeleteMail_VALUE = 1300;
    /**
     * <pre>
     ** 夺宝商城接口错误 
     * </pre>
     *
     * <code>errSnatch = 1400;</code>
     */
    public static final int errSnatch_VALUE = 1400;
    /**
     * <pre>
     ** 获取夺宝商城主界面报错 
     * </pre>
     *
     * <code>errSnatchGetList = 1401;</code>
     */
    public static final int errSnatchGetList_VALUE = 1401;
    /**
     * <pre>
     ** 夺宝-下注值超过能下注值 
     * </pre>
     *
     * <code>errSnatchInvaildBet = 1402;</code>
     */
    public static final int errSnatchInvaildBet_VALUE = 1402;
    /**
     * <pre>
     ** 夺宝-红包不足下注 
     * </pre>
     *
     * <code>errSnatchWincupNotEnough = 1403;</code>
     */
    public static final int errSnatchWincupNotEnough_VALUE = 1403;
    /**
     * <pre>
     ** 夺宝-不能领取奖励 
     * </pre>
     *
     * <code>errSnatchInvaildGetAward = 1404;</code>
     */
    public static final int errSnatchInvaildGetAward_VALUE = 1404;
    /**
     * <pre>
     ** 夺宝-已经没有更多的历史记录了
     * </pre>
     *
     * <code>errSnatchNoMoreHistories = 1405;</code>
     */
    public static final int errSnatchNoMoreHistories_VALUE = 1405;
    /**
     * <pre>
     ** 夺宝-没有填写详细的地址信息，不能领取实物奖励 
     * </pre>
     *
     * <code>errSnatchRequireAddrDetail = 1406;</code>
     */
    public static final int errSnatchRequireAddrDetail_VALUE = 1406;
    /**
     * <pre>
     ** 夺宝投入最少为100 
     * </pre>
     *
     * <code>errSnatchRequire = 1407;</code>
     */
    public static final int errSnatchRequire_VALUE = 1407;
    /**
     * <pre>
     ** 钻石宝箱接口错误 
     * </pre>
     *
     * <code>errDG = 1500;</code>
     */
    public static final int errDG_VALUE = 1500;
    /**
     * <pre>
     **钻石宝箱已经过期 
     * </pre>
     *
     * <code>errDGExpired = 1501;</code>
     */
    public static final int errDGExpired_VALUE = 1501;
    /**
     * <pre>
     ** 宝箱已经抽取完了,请重置 
     * </pre>
     *
     * <code>errBoxIsOver = 1502;</code>
     */
    public static final int errBoxIsOver_VALUE = 1502;
    /**
     * <pre>
     ** 重置失败 
     * </pre>
     *
     * <code>errReset = 1503;</code>
     */
    public static final int errReset_VALUE = 1503;
    /**
     * <pre>
     ** 游戏开启失败 
     * </pre>
     *
     * <code>errOpenDg = 1504;</code>
     */
    public static final int errOpenDg_VALUE = 1504;
    /**
     * <pre>
     ** 可重置没有重置机会 
     * </pre>
     *
     * <code>errNoLeftCont = 1505;</code>
     */
    public static final int errNoLeftCont_VALUE = 1505;
    /**
     * <pre>
     ** 重置机会用完了 
     * </pre>
     *
     * <code>errNoChance = 1506;</code>
     */
    public static final int errNoChance_VALUE = 1506;
    /**
     * <pre>
     ** 道具背包接口报错
     * </pre>
     *
     * <code>errProp = 1600;</code>
     */
    public static final int errProp_VALUE = 1600;
    /**
     * <pre>
     ** 没有这个道具报错
     * </pre>
     *
     * <code>errPropNotHaveThisProp = 1601;</code>
     */
    public static final int errPropNotHaveThisProp_VALUE = 1601;
    /**
     * <pre>
     ** 不满足道具使用条件 
     * </pre>
     *
     * <code>errNotMatchUseCondition = 1602;</code>
     */
    public static final int errNotMatchUseCondition_VALUE = 1602;
    /**
     * <pre>
     ** 签到接口错误 
     * </pre>
     *
     * <code>errSign = 1700;</code>
     */
    public static final int errSign_VALUE = 1700;
    /**
     * <pre>
     ** 重复签到 
     * </pre>
     *
     * <code>errSignRepeate = 1701;</code>
     */
    public static final int errSignRepeate_VALUE = 1701;
    /**
     * <pre>
     ** 补签卡不足 
     * </pre>
     *
     * <code>errSignRSCNotEnough = 1702;</code>
     */
    public static final int errSignRSCNotEnough_VALUE = 1702;
    /**
     * <pre>
     ** 钻石不足 
     * </pre>
     *
     * <code>errSignRSDNotEnough = 1703;</code>
     */
    public static final int errSignRSDNotEnough_VALUE = 1703;
    /**
     * <pre>
     ** 签到时间错误 
     * </pre>
     *
     * <code>errSignTime = 1704;</code>
     */
    public static final int errSignTime_VALUE = 1704;
    /**
     * <pre>
     ** 幸运时钟抽奖失败 
     * </pre>
     *
     * <code>errSignLT = 1705;</code>
     */
    public static final int errSignLT_VALUE = 1705;
    /**
     * <pre>
     ** vip等级不足 
     * </pre>
     *
     * <code>errSignVipLack = 1706;</code>
     */
    public static final int errSignVipLack_VALUE = 1706;
    /**
     * <pre>
     ** 奖励已领取 
     * </pre>
     *
     * <code>errSignRewardHasGet = 1707;</code>
     */
    public static final int errSignRewardHasGet_VALUE = 1707;
    /**
     * <pre>
     ** 签到时间不足 
     * </pre>
     *
     * <code>errSignDayNotEnough = 1708;</code>
     */
    public static final int errSignDayNotEnough_VALUE = 1708;
    /**
     * <pre>
     ** VIP接口错误 
     * </pre>
     *
     * <code>errVipLvNotEnough = 1801;</code>
     */
    public static final int errVipLvNotEnough_VALUE = 1801;
    /**
     * <pre>
     ** 本周已经领过每周奖励了 
     * </pre>
     *
     * <code>errVipWeekAwardAlreadyGet = 1802;</code>
     */
    public static final int errVipWeekAwardAlreadyGet_VALUE = 1802;
    /**
     * <pre>
     ** 已经领过每日礼包了 
     * </pre>
     *
     * <code>errVipAlreadyGetDayGift = 1803;</code>
     */
    public static final int errVipAlreadyGetDayGift_VALUE = 1803;
    /**
     * <pre>
     ** 因为昨天没抽奖，所以没有领取每日礼包的资格 
     * </pre>
     *
     * <code>errVipNotLottery = 1804;</code>
     */
    public static final int errVipNotLottery_VALUE = 1804;
    /**
     * <pre>
     ** 钻石滚动抽奖接口错误 
     * </pre>
     *
     * <code>errDD = 1900;</code>
     */
    public static final int errDD_VALUE = 1900;
    /**
     * <pre>
     ** 钻石不足 
     * </pre>
     *
     * <code>errDNotEnough = 1901;</code>
     */
    public static final int errDNotEnough_VALUE = 1901;
    /**
     * <pre>
     ** 该活动已关闭 
     * </pre>
     *
     * <code>errDDClose = 1902;</code>
     */
    public static final int errDDClose_VALUE = 1902;
    /**
     * <pre>
     ** 剩余次数不足 
     * </pre>
     *
     * <code>errDTimesNotEnough = 1903;</code>
     */
    public static final int errDTimesNotEnough_VALUE = 1903;
    /**
     * <pre>
     ** 拥有的钻石超过复活限制 
     * </pre>
     *
     * <code>errReviveExceedLimit = 2001;</code>
     */
    public static final int errReviveExceedLimit_VALUE = 2001;
    /**
     * <pre>
     ** 玩家复活次数不足 
     * </pre>
     *
     * <code>errReviveNotEnough = 2002;</code>
     */
    public static final int errReviveNotEnough_VALUE = 2002;
    /**
     * <pre>
     ** 拥有的金币超过复活限制 
     * </pre>
     *
     * <code>errReviveGoldLimit = 2003;</code>
     */
    public static final int errReviveGoldLimit_VALUE = 2003;
    /**
     * <pre>
     ** 该局比赛报名已经结束 
     * </pre>
     *
     * <code>errMatchApplyOver = 2101;</code>
     */
    public static final int errMatchApplyOver_VALUE = 2101;
    /**
     * <pre>
     ** 报名卡不足 
     * </pre>
     *
     * <code>errMatchApplyCardNotEnough = 2102;</code>
     */
    public static final int errMatchApplyCardNotEnough_VALUE = 2102;
    /**
     * <pre>
     ** 取消报名失败 
     * </pre>
     *
     * <code>errMatchCancelFail = 2103;</code>
     */
    public static final int errMatchCancelFail_VALUE = 2103;
    /**
     * <pre>
     ** 报名至少需要50钻石 
     * </pre>
     *
     * <code>errMatchEnterLimitDiamond = 2104;</code>
     */
    public static final int errMatchEnterLimitDiamond_VALUE = 2104;
    /**
     * <pre>
     ** 报名至少需要100金豆 
     * </pre>
     *
     * <code>errMatchEnterLimitGold = 2105;</code>
     */
    public static final int errMatchEnterLimitGold_VALUE = 2105;
    /**
     * <pre>
     ** 该局比赛已经结束 
     * </pre>
     *
     * <code>errMatchAlreadyOver = 2106;</code>
     */
    public static final int errMatchAlreadyOver_VALUE = 2106;
    /**
     * <pre>
     ** 你已经在其他比赛中了 
     * </pre>
     *
     * <code>errAlreadyInMatch = 2107;</code>
     */
    public static final int errAlreadyInMatch_VALUE = 2107;
    /**
     * <pre>
     ** 实名认证报错 
     * </pre>
     *
     * <code>errIdVerify = 2201;</code>
     */
    public static final int errIdVerify_VALUE = 2201;
    /**
     * <pre>
     ** 身份证格式不正确 
     * </pre>
     *
     * <code>errIdVerifyFormat = 2202;</code>
     */
    public static final int errIdVerifyFormat_VALUE = 2202;
    /**
     * <pre>
     ** 已经认证成功 
     * </pre>
     *
     * <code>errRepeateIdVerify = 2203;</code>
     */
    public static final int errRepeateIdVerify_VALUE = 2203;
    /**
     * <pre>
     ** 金豆不足 
     * </pre>
     *
     * <code>errGoldNotEnough = 2301;</code>
     */
    public static final int errGoldNotEnough_VALUE = 2301;
    /**
     * <pre>
     ** 钻石不足 
     * </pre>
     *
     * <code>errDiamondNotEnough = 2302;</code>
     */
    public static final int errDiamondNotEnough_VALUE = 2302;
    /**
     * <pre>
     ** 今日游戏次数已经用完了 
     * </pre>
     *
     * <code>errPlayTimesOver = 2303;</code>
     */
    public static final int errPlayTimesOver_VALUE = 2303;
    /**
     * <pre>
     ** 钥匙不够 
     * </pre>
     *
     * <code>errKeyNotEnough = 2304;</code>
     */
    public static final int errKeyNotEnough_VALUE = 2304;
    /**
     * <pre>
     ** cdkey兑换失败 
     * </pre>
     *
     * <code>errCdkeyFaild = 2401;</code>
     */
    public static final int errCdkeyFaild_VALUE = 2401;
    /**
     * <pre>
     ** cdkey兑换码不存在 
     * </pre>
     *
     * <code>errCdkeyErr = 2402;</code>
     */
    public static final int errCdkeyErr_VALUE = 2402;
    /**
     * <pre>
     ** cdkey兑换码已过期 
     * </pre>
     *
     * <code>errCdkeyExpired = 2403;</code>
     */
    public static final int errCdkeyExpired_VALUE = 2403;
    /**
     * <pre>
     ** cdkey兑换码已领取 
     * </pre>
     *
     * <code>errCdkeyReceived = 2404;</code>
     */
    public static final int errCdkeyReceived_VALUE = 2404;
    /**
     * <pre>
     ** cdkey兑换码已领完 
     * </pre>
     *
     * <code>errCdkeyGetOver = 2405;</code>
     */
    public static final int errCdkeyGetOver_VALUE = 2405;
    /**
     * <pre>
     ** 财神红包错误码 
     * </pre>
     *
     * <code>errGodLight = 2500;</code>
     */
    public static final int errGodLight_VALUE = 2500;
    /**
     * <pre>
     ** 不是红包活动参与者 
     * </pre>
     *
     * <code>errGodLightNotJoiner = 2501;</code>
     */
    public static final int errGodLightNotJoiner_VALUE = 2501;
    /**
     * <pre>
     ** 活动尚未开始 
     * </pre>
     *
     * <code>errGodLightActiveNotOpen = 2502;</code>
     */
    public static final int errGodLightActiveNotOpen_VALUE = 2502;
    /**
     * <pre>
     ** 玩家所在房间不在活动范围 
     * </pre>
     *
     * <code>errGodLightRoomNotAllow = 2503;</code>
     */
    public static final int errGodLightRoomNotAllow_VALUE = 2503;
    /**
     * <pre>
     ** 本轮发奖已经结束了 
     * </pre>
     *
     * <code>errGodLightNotAward = 2504;</code>
     */
    public static final int errGodLightNotAward_VALUE = 2504;
    /**
     * <pre>
     ** 本轮已经领过了 
     * </pre>
     *
     * <code>errGodLightAlreadyAwardThisTurn = 2505;</code>
     */
    public static final int errGodLightAlreadyAwardThisTurn_VALUE = 2505;
    /**
     * <pre>
     ** 手慢了，红包已经抢完了，下次加油 
     * </pre>
     *
     * <code>errGodFightNextTime = 2506;</code>
     */
    public static final int errGodFightNextTime_VALUE = 2506;
    /**
     * <pre>
     ** 古尔邦节活动错误码 
     * </pre>
     *
     * <code>errCorban = 2600;</code>
     */
    public static final int errCorban_VALUE = 2600;
    /**
     * <pre>
     ** 该奖励今日已经领取 
     * </pre>
     *
     * <code>errCorbanRepeateGet = 2601;</code>
     */
    public static final int errCorbanRepeateGet_VALUE = 2601;
    /**
     * <pre>
     ** 请在活动时间领取 
     * </pre>
     *
     * <code>errCorbanNotStart = 2602;</code>
     */
    public static final int errCorbanNotStart_VALUE = 2602;
    /**
     * <pre>
     ** 当前时间段只能领取一次 
     * </pre>
     *
     * <code>errThisTimeGetOnce = 2603;</code>
     */
    public static final int errThisTimeGetOnce_VALUE = 2603;
    /**
     * <pre>
     ** 奖励已领取 
     * </pre>
     *
     * <code>errRankShareAwardHasGet = 2701;</code>
     */
    public static final int errRankShareAwardHasGet_VALUE = 2701;
    /**
     * <pre>
     ** 成就奖励领取错误 
     * </pre>
     *
     * <code>errGetAchievementAward = 2801;</code>
     */
    public static final int errGetAchievementAward_VALUE = 2801;
    /**
     * <pre>
     ** 活动已过期 
     * </pre>
     *
     * <code>errActivityExpire = 2901;</code>
     */
    public static final int errActivityExpire_VALUE = 2901;
    /**
     * <pre>
     ** 实物商城领取次数超限 
     * </pre>
     *
     * <code>errPhysicalStoreLimit = 2902;</code>
     */
    public static final int errPhysicalStoreLimit_VALUE = 2902;
    /**
     * <pre>
     ** 活动积分不足 
     * </pre>
     *
     * <code>errScoreNotEnough = 3001;</code>
     */
    public static final int errScoreNotEnough_VALUE = 3001;
    /**
     * <pre>
     ** 请在第7天来领取 
     * </pre>
     *
     * <code>errAdvanceReceive = 3002;</code>
     */
    public static final int errAdvanceReceive_VALUE = 3002;
    /**
     * <pre>
     ** 兑换次数超限 
     * </pre>
     *
     * <code>errConvertLimit = 3003;</code>
     */
    public static final int errConvertLimit_VALUE = 3003;
    /**
     * <pre>
     ** 奖励已经领取 
     * </pre>
     *
     * <code>errHaveGetAward = 3004;</code>
     */
    public static final int errHaveGetAward_VALUE = 3004;
    /**
     * <pre>
     ** 拉取数字已达上限 
     * </pre>
     *
     * <code>errPullMax = 3005;</code>
     */
    public static final int errPullMax_VALUE = 3005;
    /**
     * <pre>
     ** 玩家进入场次货币不足 
     * </pre>
     *
     * <code>errGoldenNotEnough = 3101;</code>
     */
    public static final int errGoldenNotEnough_VALUE = 3101;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCode valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCode forNumber(int value) {
      switch (value) {
        case 0: return success;
        case 1: return err;
        case 2: return errNoMethod;
        case 3: return errNulMsg;
        case 4: return errLoginInvalid;
        case 5: return errNetConnect;
        case 6: return errGameNotOver;
        case 100: return errLogin;
        case 101: return errLoginTokenInvalid;
        case 102: return errLoginBan;
        case 103: return errLoginReconnect;
        case 300: return errRank;
        case 301: return errRankEmpty;
        case 400: return errLottery;
        case 401: return errLotteryNotEnough;
        case 500: return errShop;
        case 501: return errShopItemNotExist;
        case 502: return errShopChipNotEnough;
        case 503: return errDailyGiftNoLeft;
        case 504: return errGoldcoinResGiftNoLeft;
        case 505: return errDiamondResGiftNoLeft;
        case 506: return errUnmatchBuyResGift;
        case 507: return errNotFollowWxAccount;
        case 508: return errConvertFailed;
        case 509: return errNotBindTel;
        case 510: return errEnPayNoMoney;
        case 511: return errWxRedNoMoney;
        case 512: return errChargeOver;
        case 513: return errWxSystemError;
        case 514: return errLotteryWaitTime;
        case 515: return errExchangeExhaust;
        case 516: return errChargeOrJdCard;
        case 600: return errRoom;
        case 601: return errRoomChipNotEnough;
        case 602: return errRoomDiamondNotEnough;
        case 603: return errRoomNotExist;
        case 604: return errRoomNotIn;
        case 605: return errRoomChipToMuch;
        case 606: return errRoomDiamondToMuch;
        case 607: return errRoomInMatch;
        case 701: return errUserIsNull;
        case 800: return errGame;
        case 801: return errGameRoomNotExist;
        case 802: return errGameAutoPlay;
        case 803: return errGameInvaildOper;
        case 804: return errGameInvaildCatchPoint;
        case 805: return errGameEnterRoomFail;
        case 806: return errGamePlayerNotIn;
        case 807: return errGameCardInvaild;
        case 808: return errGameSendActionTime;
        case 900: return errPm;
        case 901: return errPmTelNumInvaild;
        case 902: return errPmVerifyCodeFail;
        case 903: return errPmGetAwardNotFinish;
        case 904: return errPmGetAwardNotBindTel;
        case 905: return errPmAlreadyBind;
        case 906: return errPmRequestIntervalTooShort;
        case 907: return errPmSharePackageFail;
        case 908: return errPmNoSlave;
        case 909: return errPmNotRelationship;
        case 910: return errPmTelAlreadyUsed;
        case 1000: return errAwardMsgIsNul;
        case 1100: return errGetDailyFailed;
        case 1200: return errNoviceTaskexpired;
        case 1201: return errGetNoviceFailed;
        case 1300: return errDeleteMail;
        case 1400: return errSnatch;
        case 1401: return errSnatchGetList;
        case 1402: return errSnatchInvaildBet;
        case 1403: return errSnatchWincupNotEnough;
        case 1404: return errSnatchInvaildGetAward;
        case 1405: return errSnatchNoMoreHistories;
        case 1406: return errSnatchRequireAddrDetail;
        case 1407: return errSnatchRequire;
        case 1500: return errDG;
        case 1501: return errDGExpired;
        case 1502: return errBoxIsOver;
        case 1503: return errReset;
        case 1504: return errOpenDg;
        case 1505: return errNoLeftCont;
        case 1506: return errNoChance;
        case 1600: return errProp;
        case 1601: return errPropNotHaveThisProp;
        case 1602: return errNotMatchUseCondition;
        case 1700: return errSign;
        case 1701: return errSignRepeate;
        case 1702: return errSignRSCNotEnough;
        case 1703: return errSignRSDNotEnough;
        case 1704: return errSignTime;
        case 1705: return errSignLT;
        case 1706: return errSignVipLack;
        case 1707: return errSignRewardHasGet;
        case 1708: return errSignDayNotEnough;
        case 1801: return errVipLvNotEnough;
        case 1802: return errVipWeekAwardAlreadyGet;
        case 1803: return errVipAlreadyGetDayGift;
        case 1804: return errVipNotLottery;
        case 1900: return errDD;
        case 1901: return errDNotEnough;
        case 1902: return errDDClose;
        case 1903: return errDTimesNotEnough;
        case 2001: return errReviveExceedLimit;
        case 2002: return errReviveNotEnough;
        case 2003: return errReviveGoldLimit;
        case 2101: return errMatchApplyOver;
        case 2102: return errMatchApplyCardNotEnough;
        case 2103: return errMatchCancelFail;
        case 2104: return errMatchEnterLimitDiamond;
        case 2105: return errMatchEnterLimitGold;
        case 2106: return errMatchAlreadyOver;
        case 2107: return errAlreadyInMatch;
        case 2201: return errIdVerify;
        case 2202: return errIdVerifyFormat;
        case 2203: return errRepeateIdVerify;
        case 2301: return errGoldNotEnough;
        case 2302: return errDiamondNotEnough;
        case 2303: return errPlayTimesOver;
        case 2304: return errKeyNotEnough;
        case 2401: return errCdkeyFaild;
        case 2402: return errCdkeyErr;
        case 2403: return errCdkeyExpired;
        case 2404: return errCdkeyReceived;
        case 2405: return errCdkeyGetOver;
        case 2500: return errGodLight;
        case 2501: return errGodLightNotJoiner;
        case 2502: return errGodLightActiveNotOpen;
        case 2503: return errGodLightRoomNotAllow;
        case 2504: return errGodLightNotAward;
        case 2505: return errGodLightAlreadyAwardThisTurn;
        case 2506: return errGodFightNextTime;
        case 2600: return errCorban;
        case 2601: return errCorbanRepeateGet;
        case 2602: return errCorbanNotStart;
        case 2603: return errThisTimeGetOnce;
        case 2701: return errRankShareAwardHasGet;
        case 2801: return errGetAchievementAward;
        case 2901: return errActivityExpire;
        case 2902: return errPhysicalStoreLimit;
        case 3001: return errScoreNotEnough;
        case 3002: return errAdvanceReceive;
        case 3003: return errConvertLimit;
        case 3004: return errHaveGetAward;
        case 3005: return errPullMax;
        case 3101: return errGoldenNotEnough;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResultCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
            public ResultCode findValueByNumber(int number) {
              return ResultCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kys.pb.PbCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResultCode[] VALUES = values();

    public static ResultCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResultCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pb.ResultCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017pb_result.proto\022\002pb*\253\032\n\nResultCode\022\013\n\007" +
      "success\020\000\022\007\n\003err\020\001\022\017\n\013errNoMethod\020\002\022\r\n\te" +
      "rrNulMsg\020\003\022\023\n\017errLoginInvalid\020\004\022\021\n\rerrNe" +
      "tConnect\020\005\022\022\n\016errGameNotOver\020\006\022\014\n\010errLog" +
      "in\020d\022\030\n\024errLoginTokenInvalid\020e\022\017\n\013errLog" +
      "inBan\020f\022\025\n\021errLoginReconnect\020g\022\014\n\007errRan" +
      "k\020\254\002\022\021\n\014errRankEmpty\020\255\002\022\017\n\nerrLottery\020\220\003" +
      "\022\030\n\023errLotteryNotEnough\020\221\003\022\014\n\007errShop\020\364\003" +
      "\022\030\n\023errShopItemNotExist\020\365\003\022\031\n\024errShopChi" +
      "pNotEnough\020\366\003\022\027\n\022errDailyGiftNoLeft\020\367\003\022\035" +
      "\n\030errGoldcoinResGiftNoLeft\020\370\003\022\034\n\027errDiam" +
      "ondResGiftNoLeft\020\371\003\022\031\n\024errUnmatchBuyResG" +
      "ift\020\372\003\022\032\n\025errNotFollowWxAccount\020\373\003\022\025\n\020er" +
      "rConvertFailed\020\374\003\022\022\n\rerrNotBindTel\020\375\003\022\024\n" +
      "\017errEnPayNoMoney\020\376\003\022\024\n\017errWxRedNoMoney\020\377" +
      "\003\022\022\n\rerrChargeOver\020\200\004\022\025\n\020errWxSystemErro" +
      "r\020\201\004\022\027\n\022errLotteryWaitTime\020\202\004\022\027\n\022errExch" +
      "angeExhaust\020\203\004\022\026\n\021errChargeOrJdCard\020\204\004\022\014" +
      "\n\007errRoom\020\330\004\022\031\n\024errRoomChipNotEnough\020\331\004\022" +
      "\034\n\027errRoomDiamondNotEnough\020\332\004\022\024\n\017errRoom" +
      "NotExist\020\333\004\022\021\n\014errRoomNotIn\020\334\004\022\026\n\021errRoo" +
      "mChipToMuch\020\335\004\022\031\n\024errRoomDiamondToMuch\020\336" +
      "\004\022\023\n\016errRoomInMatch\020\337\004\022\022\n\rerrUserIsNull\020" +
      "\275\005\022\014\n\007errGame\020\240\006\022\030\n\023errGameRoomNotExist\020" +
      "\241\006\022\024\n\017errGameAutoPlay\020\242\006\022\027\n\022errGameInvai" +
      "ldOper\020\243\006\022\035\n\030errGameInvaildCatchPoint\020\244\006" +
      "\022\031\n\024errGameEnterRoomFail\020\245\006\022\027\n\022errGamePl" +
      "ayerNotIn\020\246\006\022\027\n\022errGameCardInvaild\020\247\006\022\032\n" +
      "\025errGameSendActionTime\020\250\006\022\n\n\005errPm\020\204\007\022\027\n" +
      "\022errPmTelNumInvaild\020\205\007\022\030\n\023errPmVerifyCod" +
      "eFail\020\206\007\022\033\n\026errPmGetAwardNotFinish\020\207\007\022\034\n" +
      "\027errPmGetAwardNotBindTel\020\210\007\022\025\n\020errPmAlre" +
      "adyBind\020\211\007\022!\n\034errPmRequestIntervalTooSho" +
      "rt\020\212\007\022\032\n\025errPmSharePackageFail\020\213\007\022\021\n\014err" +
      "PmNoSlave\020\214\007\022\031\n\024errPmNotRelationship\020\215\007\022" +
      "\030\n\023errPmTelAlreadyUsed\020\216\007\022\025\n\020errAwardMsg" +
      "IsNul\020\350\007\022\026\n\021errGetDailyFailed\020\314\010\022\031\n\024errN" +
      "oviceTaskexpired\020\260\t\022\027\n\022errGetNoviceFaile" +
      "d\020\261\t\022\022\n\rerrDeleteMail\020\224\n\022\016\n\terrSnatch\020\370\n" +
      "\022\025\n\020errSnatchGetList\020\371\n\022\030\n\023errSnatchInva" +
      "ildBet\020\372\n\022\035\n\030errSnatchWincupNotEnough\020\373\n" +
      "\022\035\n\030errSnatchInvaildGetAward\020\374\n\022\035\n\030errSn" +
      "atchNoMoreHistories\020\375\n\022\037\n\032errSnatchRequi" +
      "reAddrDetail\020\376\n\022\025\n\020errSnatchRequire\020\377\n\022\n" +
      "\n\005errDG\020\334\013\022\021\n\014errDGExpired\020\335\013\022\021\n\014errBoxI" +
      "sOver\020\336\013\022\r\n\010errReset\020\337\013\022\016\n\terrOpenDg\020\340\013\022" +
      "\022\n\rerrNoLeftCont\020\341\013\022\020\n\013errNoChance\020\342\013\022\014\n" +
      "\007errProp\020\300\014\022\033\n\026errPropNotHaveThisProp\020\301\014" +
      "\022\034\n\027errNotMatchUseCondition\020\302\014\022\014\n\007errSig" +
      "n\020\244\r\022\023\n\016errSignRepeate\020\245\r\022\030\n\023errSignRSCN" +
      "otEnough\020\246\r\022\030\n\023errSignRSDNotEnough\020\247\r\022\020\n" +
      "\013errSignTime\020\250\r\022\016\n\terrSignLT\020\251\r\022\023\n\016errSi" +
      "gnVipLack\020\252\r\022\030\n\023errSignRewardHasGet\020\253\r\022\030" +
      "\n\023errSignDayNotEnough\020\254\r\022\026\n\021errVipLvNotE" +
      "nough\020\211\016\022\036\n\031errVipWeekAwardAlreadyGet\020\212\016" +
      "\022\034\n\027errVipAlreadyGetDayGift\020\213\016\022\025\n\020errVip" +
      "NotLottery\020\214\016\022\n\n\005errDD\020\354\016\022\022\n\rerrDNotEnou" +
      "gh\020\355\016\022\017\n\nerrDDClose\020\356\016\022\027\n\022errDTimesNotEn" +
      "ough\020\357\016\022\031\n\024errReviveExceedLimit\020\321\017\022\027\n\022er" +
      "rReviveNotEnough\020\322\017\022\027\n\022errReviveGoldLimi" +
      "t\020\323\017\022\026\n\021errMatchApplyOver\020\265\020\022\037\n\032errMatch" +
      "ApplyCardNotEnough\020\266\020\022\027\n\022errMatchCancelF" +
      "ail\020\267\020\022\036\n\031errMatchEnterLimitDiamond\020\270\020\022\033" +
      "\n\026errMatchEnterLimitGold\020\271\020\022\030\n\023errMatchA" +
      "lreadyOver\020\272\020\022\026\n\021errAlreadyInMatch\020\273\020\022\020\n" +
      "\013errIdVerify\020\231\021\022\026\n\021errIdVerifyFormat\020\232\021\022" +
      "\027\n\022errRepeateIdVerify\020\233\021\022\025\n\020errGoldNotEn" +
      "ough\020\375\021\022\030\n\023errDiamondNotEnough\020\376\021\022\025\n\020err" +
      "PlayTimesOver\020\377\021\022\024\n\017errKeyNotEnough\020\200\022\022\022" +
      "\n\rerrCdkeyFaild\020\341\022\022\020\n\013errCdkeyErr\020\342\022\022\024\n\017" +
      "errCdkeyExpired\020\343\022\022\025\n\020errCdkeyReceived\020\344" +
      "\022\022\024\n\017errCdkeyGetOver\020\345\022\022\020\n\013errGodLight\020\304" +
      "\023\022\031\n\024errGodLightNotJoiner\020\305\023\022\035\n\030errGodLi" +
      "ghtActiveNotOpen\020\306\023\022\034\n\027errGodLightRoomNo" +
      "tAllow\020\307\023\022\030\n\023errGodLightNotAward\020\310\023\022$\n\037e" +
      "rrGodLightAlreadyAwardThisTurn\020\311\023\022\030\n\023err" +
      "GodFightNextTime\020\312\023\022\016\n\terrCorban\020\250\024\022\030\n\023e" +
      "rrCorbanRepeateGet\020\251\024\022\026\n\021errCorbanNotSta" +
      "rt\020\252\024\022\027\n\022errThisTimeGetOnce\020\253\024\022\034\n\027errRan" +
      "kShareAwardHasGet\020\215\025\022\033\n\026errGetAchievemen" +
      "tAward\020\361\025\022\026\n\021errActivityExpire\020\325\026\022\032\n\025err" +
      "PhysicalStoreLimit\020\326\026\022\026\n\021errScoreNotEnou" +
      "gh\020\271\027\022\026\n\021errAdvanceReceive\020\272\027\022\024\n\017errConv" +
      "ertLimit\020\273\027\022\024\n\017errHaveGetAward\020\274\027\022\017\n\nerr" +
      "PullMax\020\275\027\022\027\n\022errGoldenNotEnough\020\235\030B\024\n\nc" +
      "om.kys.pbB\006PbCodeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
