// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb.proto

package com.kys.pb;

public final class PbGate {
  private PbGate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   ** 服务类型 
   * </pre>
   *
   * Protobuf enum {@code pb.ServiceType}
   */
  public enum ServiceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOW_SERVICE = 0;</code>
     */
    UNKNOW_SERVICE(0),
    /**
     * <pre>
     ** 网关服 
     * </pre>
     *
     * <code>GATEWAY = 1;</code>
     */
    GATEWAY(1),
    /**
     * <pre>
     ** 平台服 
     * </pre>
     *
     * <code>PLATFORM = 2;</code>
     */
    PLATFORM(2),
    /**
     * <pre>
     ** 地主服 
     * </pre>
     *
     * <code>LANDLORD = 3;</code>
     */
    LANDLORD(3),
    /**
     * <pre>
     ** 捕鱼服 
     * </pre>
     *
     * <code>CATCHFISH = 4;</code>
     */
    CATCHFISH(4),
    /**
     * <pre>
     ** 台球服 
     * </pre>
     *
     * <code>BILLIARD = 5;</code>
     */
    BILLIARD(5),
    /**
     * <pre>
     ** 消消乐 
     * </pre>
     *
     * <code>ELIMINATE = 6;</code>
     */
    ELIMINATE(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOW_SERVICE = 0;</code>
     */
    public static final int UNKNOW_SERVICE_VALUE = 0;
    /**
     * <pre>
     ** 网关服 
     * </pre>
     *
     * <code>GATEWAY = 1;</code>
     */
    public static final int GATEWAY_VALUE = 1;
    /**
     * <pre>
     ** 平台服 
     * </pre>
     *
     * <code>PLATFORM = 2;</code>
     */
    public static final int PLATFORM_VALUE = 2;
    /**
     * <pre>
     ** 地主服 
     * </pre>
     *
     * <code>LANDLORD = 3;</code>
     */
    public static final int LANDLORD_VALUE = 3;
    /**
     * <pre>
     ** 捕鱼服 
     * </pre>
     *
     * <code>CATCHFISH = 4;</code>
     */
    public static final int CATCHFISH_VALUE = 4;
    /**
     * <pre>
     ** 台球服 
     * </pre>
     *
     * <code>BILLIARD = 5;</code>
     */
    public static final int BILLIARD_VALUE = 5;
    /**
     * <pre>
     ** 消消乐 
     * </pre>
     *
     * <code>ELIMINATE = 6;</code>
     */
    public static final int ELIMINATE_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ServiceType valueOf(int value) {
      return forNumber(value);
    }

    public static ServiceType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOW_SERVICE;
        case 1: return GATEWAY;
        case 2: return PLATFORM;
        case 3: return LANDLORD;
        case 4: return CATCHFISH;
        case 5: return BILLIARD;
        case 6: return ELIMINATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServiceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServiceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceType>() {
            public ServiceType findValueByNumber(int number) {
              return ServiceType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kys.pb.PbGate.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServiceType[] VALUES = values();

    public static ServiceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServiceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pb.ServiceType)
  }

  /**
   * <pre>
   ** 网关消息号
   * </pre>
   *
   * Protobuf enum {@code pb.MSG}
   */
  public enum MSG
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWNGATEWAYCMD = 0;</code>
     */
    UNKNOWNGATEWAYCMD(0),
    /**
     * <pre>
     ** 心跳消息
     * </pre>
     *
     * <code>HEARTBEAT = 1;</code>
     */
    HEARTBEAT(1),
    /**
     * <pre>
     ** 踢人的消息
     * </pre>
     *
     * <code>KICKOFF = 2;</code>
     */
    KICKOFF(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWNGATEWAYCMD = 0;</code>
     */
    public static final int UNKNOWNGATEWAYCMD_VALUE = 0;
    /**
     * <pre>
     ** 心跳消息
     * </pre>
     *
     * <code>HEARTBEAT = 1;</code>
     */
    public static final int HEARTBEAT_VALUE = 1;
    /**
     * <pre>
     ** 踢人的消息
     * </pre>
     *
     * <code>KICKOFF = 2;</code>
     */
    public static final int KICKOFF_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MSG valueOf(int value) {
      return forNumber(value);
    }

    public static MSG forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWNGATEWAYCMD;
        case 1: return HEARTBEAT;
        case 2: return KICKOFF;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MSG>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MSG> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MSG>() {
            public MSG findValueByNumber(int number) {
              return MSG.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kys.pb.PbGate.getDescriptor().getEnumTypes().get(1);
    }

    private static final MSG[] VALUES = values();

    public static MSG valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MSG(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pb.MSG)
  }

  public interface HeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.Heartbeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 服务器时间戳，单位到毫秒
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    long getTime();

    /**
     * <pre>
     ** 消息延时,单位是毫秒
     * </pre>
     *
     * <code>int32 delay = 2;</code>
     */
    int getDelay();
  }
  /**
   * <pre>
   ** 心跳消息
   * </pre>
   *
   * Protobuf type {@code pb.Heartbeat}
   */
  public  static final class Heartbeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.Heartbeat)
      HeartbeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Heartbeat.newBuilder() to construct.
    private Heartbeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Heartbeat() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Heartbeat();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Heartbeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              time_ = input.readInt64();
              break;
            }
            case 16: {

              delay_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_pb_Heartbeat_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_pb_Heartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kys.pb.PbGate.Heartbeat.class, com.kys.pb.PbGate.Heartbeat.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <pre>
     ** 服务器时间戳，单位到毫秒
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int DELAY_FIELD_NUMBER = 2;
    private int delay_;
    /**
     * <pre>
     ** 消息延时,单位是毫秒
     * </pre>
     *
     * <code>int32 delay = 2;</code>
     */
    public int getDelay() {
      return delay_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeInt64(1, time_);
      }
      if (delay_ != 0) {
        output.writeInt32(2, delay_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (delay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, delay_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kys.pb.PbGate.Heartbeat)) {
        return super.equals(obj);
      }
      com.kys.pb.PbGate.Heartbeat other = (com.kys.pb.PbGate.Heartbeat) obj;

      if (getTime()
          != other.getTime()) return false;
      if (getDelay()
          != other.getDelay()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + DELAY_FIELD_NUMBER;
      hash = (53 * hash) + getDelay();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kys.pb.PbGate.Heartbeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.Heartbeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kys.pb.PbGate.Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kys.pb.PbGate.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kys.pb.PbGate.Heartbeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 心跳消息
     * </pre>
     *
     * Protobuf type {@code pb.Heartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.Heartbeat)
        com.kys.pb.PbGate.HeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_pb_Heartbeat_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_pb_Heartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kys.pb.PbGate.Heartbeat.class, com.kys.pb.PbGate.Heartbeat.Builder.class);
      }

      // Construct using com.kys.pb.PbGate.Heartbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        time_ = 0L;

        delay_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_pb_Heartbeat_descriptor;
      }

      @Override
      public com.kys.pb.PbGate.Heartbeat getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.kys.pb.PbGate.Heartbeat build() {
        com.kys.pb.PbGate.Heartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.kys.pb.PbGate.Heartbeat buildPartial() {
        com.kys.pb.PbGate.Heartbeat result = new com.kys.pb.PbGate.Heartbeat(this);
        result.time_ = time_;
        result.delay_ = delay_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kys.pb.PbGate.Heartbeat) {
          return mergeFrom((com.kys.pb.PbGate.Heartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kys.pb.PbGate.Heartbeat other) {
        if (other == getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getDelay() != 0) {
          setDelay(other.getDelay());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kys.pb.PbGate.Heartbeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kys.pb.PbGate.Heartbeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       ** 服务器时间戳，单位到毫秒
       * </pre>
       *
       * <code>int64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       ** 服务器时间戳，单位到毫秒
       * </pre>
       *
       * <code>int64 time = 1;</code>
       */
      public Builder setTime(long value) {

        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 服务器时间戳，单位到毫秒
       * </pre>
       *
       * <code>int64 time = 1;</code>
       */
      public Builder clearTime() {

        time_ = 0L;
        onChanged();
        return this;
      }

      private int delay_ ;
      /**
       * <pre>
       ** 消息延时,单位是毫秒
       * </pre>
       *
       * <code>int32 delay = 2;</code>
       */
      public int getDelay() {
        return delay_;
      }
      /**
       * <pre>
       ** 消息延时,单位是毫秒
       * </pre>
       *
       * <code>int32 delay = 2;</code>
       */
      public Builder setDelay(int value) {

        delay_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 消息延时,单位是毫秒
       * </pre>
       *
       * <code>int32 delay = 2;</code>
       */
      public Builder clearDelay() {

        delay_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.Heartbeat)
    }

    // @@protoc_insertion_point(class_scope:pb.Heartbeat)
    private static final com.kys.pb.PbGate.Heartbeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kys.pb.PbGate.Heartbeat();
    }

    public static com.kys.pb.PbGate.Heartbeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Heartbeat>
        PARSER = new com.google.protobuf.AbstractParser<Heartbeat>() {
      @Override
      public Heartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Heartbeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Heartbeat> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Heartbeat> getParserForType() {
      return PARSER;
    }

    @Override
    public com.kys.pb.PbGate.Heartbeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KickOffOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.KickOff)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 原因码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <pre>
     ** 踢下线的原因
     * </pre>
     *
     * <code>string reason = 2;</code>
     */
    String getReason();
    /**
     * <pre>
     ** 踢下线的原因
     * </pre>
     *
     * <code>string reason = 2;</code>
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * <pre>
   ** 服务器踢人下线
   * </pre>
   *
   * Protobuf type {@code pb.KickOff}
   */
  public  static final class KickOff extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.KickOff)
      KickOffOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KickOff.newBuilder() to construct.
    private KickOff(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KickOff() {
      reason_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new KickOff();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KickOff(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              reason_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_pb_KickOff_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_pb_KickOff_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kys.pb.PbGate.KickOff.class, com.kys.pb.PbGate.KickOff.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     ** 原因码
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int REASON_FIELD_NUMBER = 2;
    private volatile Object reason_;
    /**
     * <pre>
     ** 踢下线的原因
     * </pre>
     *
     * <code>string reason = 2;</code>
     */
    public String getReason() {
      Object ref = reason_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 踢下线的原因
     * </pre>
     *
     * <code>string reason = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      Object ref = reason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reason_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reason_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kys.pb.PbGate.KickOff)) {
        return super.equals(obj);
      }
      com.kys.pb.PbGate.KickOff other = (com.kys.pb.PbGate.KickOff) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getReason()
          .equals(other.getReason())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kys.pb.PbGate.KickOff parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.KickOff parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.KickOff parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.KickOff parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.KickOff parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.KickOff parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.KickOff parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.KickOff parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kys.pb.PbGate.KickOff parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.KickOff parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kys.pb.PbGate.KickOff parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.KickOff parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kys.pb.PbGate.KickOff prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 服务器踢人下线
     * </pre>
     *
     * Protobuf type {@code pb.KickOff}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.KickOff)
        com.kys.pb.PbGate.KickOffOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_pb_KickOff_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_pb_KickOff_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kys.pb.PbGate.KickOff.class, com.kys.pb.PbGate.KickOff.Builder.class);
      }

      // Construct using com.kys.pb.PbGate.KickOff.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        reason_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_pb_KickOff_descriptor;
      }

      @Override
      public com.kys.pb.PbGate.KickOff getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.kys.pb.PbGate.KickOff build() {
        com.kys.pb.PbGate.KickOff result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.kys.pb.PbGate.KickOff buildPartial() {
        com.kys.pb.PbGate.KickOff result = new com.kys.pb.PbGate.KickOff(this);
        result.code_ = code_;
        result.reason_ = reason_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kys.pb.PbGate.KickOff) {
          return mergeFrom((com.kys.pb.PbGate.KickOff)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kys.pb.PbGate.KickOff other) {
        if (other == getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getReason().isEmpty()) {
          reason_ = other.reason_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kys.pb.PbGate.KickOff parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kys.pb.PbGate.KickOff) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       ** 原因码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       ** 原因码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {

        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 原因码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {

        code_ = 0;
        onChanged();
        return this;
      }

      private Object reason_ = "";
      /**
       * <pre>
       ** 踢下线的原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       */
      public String getReason() {
        Object ref = reason_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       ** 踢下线的原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 踢下线的原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       */
      public Builder setReason(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 踢下线的原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       */
      public Builder clearReason() {

        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 踢下线的原因
       * </pre>
       *
       * <code>string reason = 2;</code>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        reason_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.KickOff)
    }

    // @@protoc_insertion_point(class_scope:pb.KickOff)
    private static final com.kys.pb.PbGate.KickOff DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kys.pb.PbGate.KickOff();
    }

    public static com.kys.pb.PbGate.KickOff getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KickOff>
        PARSER = new com.google.protobuf.AbstractParser<KickOff>() {
      @Override
      public KickOff parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KickOff(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KickOff> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<KickOff> getParserForType() {
      return PARSER;
    }

    @Override
    public com.kys.pb.PbGate.KickOff getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2SOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.C2S)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 服务器序列
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     */
    int getSid();

    /**
     * <pre>
     ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
     * </pre>
     *
     * <code>int32 cid = 2;</code>
     */
    int getCid();

    /**
     * <pre>
     ** 消息序号，用作客户端识别服务器响应
     * </pre>
     *
     * <code>int32 sequence = 3;</code>
     */
    int getSequence();

    /**
     * <pre>
     ** 消息体数据
     * </pre>
     *
     * <code>bytes body = 4;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * <pre>
   ** 客户端向服务器发送消息
   * </pre>
   *
   * Protobuf type {@code pb.C2S}
   */
  public  static final class C2S extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.C2S)
      C2SOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S.newBuilder() to construct.
    private C2S(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new C2S();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sid_ = input.readInt32();
              break;
            }
            case 16: {

              cid_ = input.readInt32();
              break;
            }
            case 24: {

              sequence_ = input.readInt32();
              break;
            }
            case 34: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_pb_C2S_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_pb_C2S_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kys.pb.PbGate.C2S.class, com.kys.pb.PbGate.C2S.Builder.class);
    }

    public static final int SID_FIELD_NUMBER = 1;
    private int sid_;
    /**
     * <pre>
     ** 服务器序列
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     */
    public int getSid() {
      return sid_;
    }

    public static final int CID_FIELD_NUMBER = 2;
    private int cid_;
    /**
     * <pre>
     ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
     * </pre>
     *
     * <code>int32 cid = 2;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 3;
    private int sequence_;
    /**
     * <pre>
     ** 消息序号，用作客户端识别服务器响应
     * </pre>
     *
     * <code>int32 sequence = 3;</code>
     */
    public int getSequence() {
      return sequence_;
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     ** 消息体数据
     * </pre>
     *
     * <code>bytes body = 4;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sid_ != 0) {
        output.writeInt32(1, sid_);
      }
      if (cid_ != 0) {
        output.writeInt32(2, cid_);
      }
      if (sequence_ != 0) {
        output.writeInt32(3, sequence_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(4, body_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sid_);
      }
      if (cid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cid_);
      }
      if (sequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sequence_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kys.pb.PbGate.C2S)) {
        return super.equals(obj);
      }
      com.kys.pb.PbGate.C2S other = (com.kys.pb.PbGate.C2S) obj;

      if (getSid()
          != other.getSid()) return false;
      if (getCid()
          != other.getCid()) return false;
      if (getSequence()
          != other.getSequence()) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid();
      hash = (37 * hash) + CID_FIELD_NUMBER;
      hash = (53 * hash) + getCid();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kys.pb.PbGate.C2S parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.C2S parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.C2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.C2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.C2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.C2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.C2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.C2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kys.pb.PbGate.C2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.C2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kys.pb.PbGate.C2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.C2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kys.pb.PbGate.C2S prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 客户端向服务器发送消息
     * </pre>
     *
     * Protobuf type {@code pb.C2S}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.C2S)
        com.kys.pb.PbGate.C2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_pb_C2S_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_pb_C2S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kys.pb.PbGate.C2S.class, com.kys.pb.PbGate.C2S.Builder.class);
      }

      // Construct using com.kys.pb.PbGate.C2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        sid_ = 0;

        cid_ = 0;

        sequence_ = 0;

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_pb_C2S_descriptor;
      }

      @Override
      public com.kys.pb.PbGate.C2S getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.kys.pb.PbGate.C2S build() {
        com.kys.pb.PbGate.C2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.kys.pb.PbGate.C2S buildPartial() {
        com.kys.pb.PbGate.C2S result = new com.kys.pb.PbGate.C2S(this);
        result.sid_ = sid_;
        result.cid_ = cid_;
        result.sequence_ = sequence_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kys.pb.PbGate.C2S) {
          return mergeFrom((com.kys.pb.PbGate.C2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kys.pb.PbGate.C2S other) {
        if (other == getDefaultInstance()) return this;
        if (other.getSid() != 0) {
          setSid(other.getSid());
        }
        if (other.getCid() != 0) {
          setCid(other.getCid());
        }
        if (other.getSequence() != 0) {
          setSequence(other.getSequence());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kys.pb.PbGate.C2S parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kys.pb.PbGate.C2S) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sid_ ;
      /**
       * <pre>
       ** 服务器序列
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       */
      public int getSid() {
        return sid_;
      }
      /**
       * <pre>
       ** 服务器序列
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       */
      public Builder setSid(int value) {

        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 服务器序列
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       */
      public Builder clearSid() {

        sid_ = 0;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <pre>
       ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
       * </pre>
       *
       * <code>int32 cid = 2;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <pre>
       ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
       * </pre>
       *
       * <code>int32 cid = 2;</code>
       */
      public Builder setCid(int value) {

        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
       * </pre>
       *
       * <code>int32 cid = 2;</code>
       */
      public Builder clearCid() {

        cid_ = 0;
        onChanged();
        return this;
      }

      private int sequence_ ;
      /**
       * <pre>
       ** 消息序号，用作客户端识别服务器响应
       * </pre>
       *
       * <code>int32 sequence = 3;</code>
       */
      public int getSequence() {
        return sequence_;
      }
      /**
       * <pre>
       ** 消息序号，用作客户端识别服务器响应
       * </pre>
       *
       * <code>int32 sequence = 3;</code>
       */
      public Builder setSequence(int value) {

        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 消息序号，用作客户端识别服务器响应
       * </pre>
       *
       * <code>int32 sequence = 3;</code>
       */
      public Builder clearSequence() {

        sequence_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       ** 消息体数据
       * </pre>
       *
       * <code>bytes body = 4;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       ** 消息体数据
       * </pre>
       *
       * <code>bytes body = 4;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 消息体数据
       * </pre>
       *
       * <code>bytes body = 4;</code>
       */
      public Builder clearBody() {

        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.C2S)
    }

    // @@protoc_insertion_point(class_scope:pb.C2S)
    private static final com.kys.pb.PbGate.C2S DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kys.pb.PbGate.C2S();
    }

    public static com.kys.pb.PbGate.C2S getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C2S>
        PARSER = new com.google.protobuf.AbstractParser<C2S>() {
      @Override
      public C2S parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<C2S> getParserForType() {
      return PARSER;
    }

    @Override
    public com.kys.pb.PbGate.C2S getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 服务器序列
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     */
    int getSid();

    /**
     * <pre>
     ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
     * </pre>
     *
     * <code>int32 cid = 2;</code>
     */
    int getCid();

    /**
     * <pre>
     ** 消息序号，用作客户端识别服务器响应
     * </pre>
     *
     * <code>int32 sequence = 3;</code>
     */
    int getSequence();

    /**
     * <pre>
     ** 响应结果，0是成功，1是请求超时（消息已发出），2是请求错误（消息未发出），大于100是服务器响应返回的错误
     * </pre>
     *
     * <code>int32 code = 4;</code>
     */
    int getCode();

    /**
     * <pre>
     ** 消息体数据
     * </pre>
     *
     * <code>bytes body = 5;</code>
     */
    com.google.protobuf.ByteString getBody();

    /**
     * <pre>
     ** 错误信息
     * </pre>
     *
     * <code>string errStr = 6;</code>
     */
    String getErrStr();
    /**
     * <pre>
     ** 错误信息
     * </pre>
     *
     * <code>string errStr = 6;</code>
     */
    com.google.protobuf.ByteString
        getErrStrBytes();
  }
  /**
   * <pre>
   ** 服务端向客户端发送消息
   * </pre>
   *
   * Protobuf type {@code pb.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.S2C)
      S2COrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C() {
      body_ = com.google.protobuf.ByteString.EMPTY;
      errStr_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new S2C();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sid_ = input.readInt32();
              break;
            }
            case 16: {

              cid_ = input.readInt32();
              break;
            }
            case 24: {

              sequence_ = input.readInt32();
              break;
            }
            case 32: {

              code_ = input.readInt32();
              break;
            }
            case 42: {

              body_ = input.readBytes();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              errStr_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_pb_S2C_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_pb_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kys.pb.PbGate.S2C.class, com.kys.pb.PbGate.S2C.Builder.class);
    }

    public static final int SID_FIELD_NUMBER = 1;
    private int sid_;
    /**
     * <pre>
     ** 服务器序列
     * </pre>
     *
     * <code>int32 sid = 1;</code>
     */
    public int getSid() {
      return sid_;
    }

    public static final int CID_FIELD_NUMBER = 2;
    private int cid_;
    /**
     * <pre>
     ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
     * </pre>
     *
     * <code>int32 cid = 2;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 3;
    private int sequence_;
    /**
     * <pre>
     ** 消息序号，用作客户端识别服务器响应
     * </pre>
     *
     * <code>int32 sequence = 3;</code>
     */
    public int getSequence() {
      return sequence_;
    }

    public static final int CODE_FIELD_NUMBER = 4;
    private int code_;
    /**
     * <pre>
     ** 响应结果，0是成功，1是请求超时（消息已发出），2是请求错误（消息未发出），大于100是服务器响应返回的错误
     * </pre>
     *
     * <code>int32 code = 4;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int BODY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     ** 消息体数据
     * </pre>
     *
     * <code>bytes body = 5;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    public static final int ERRSTR_FIELD_NUMBER = 6;
    private volatile Object errStr_;
    /**
     * <pre>
     ** 错误信息
     * </pre>
     *
     * <code>string errStr = 6;</code>
     */
    public String getErrStr() {
      Object ref = errStr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errStr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 错误信息
     * </pre>
     *
     * <code>string errStr = 6;</code>
     */
    public com.google.protobuf.ByteString
        getErrStrBytes() {
      Object ref = errStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sid_ != 0) {
        output.writeInt32(1, sid_);
      }
      if (cid_ != 0) {
        output.writeInt32(2, cid_);
      }
      if (sequence_ != 0) {
        output.writeInt32(3, sequence_);
      }
      if (code_ != 0) {
        output.writeInt32(4, code_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(5, body_);
      }
      if (!getErrStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, errStr_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sid_);
      }
      if (cid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cid_);
      }
      if (sequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sequence_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, code_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, body_);
      }
      if (!getErrStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, errStr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kys.pb.PbGate.S2C)) {
        return super.equals(obj);
      }
      com.kys.pb.PbGate.S2C other = (com.kys.pb.PbGate.S2C) obj;

      if (getSid()
          != other.getSid()) return false;
      if (getCid()
          != other.getCid()) return false;
      if (getSequence()
          != other.getSequence()) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!getErrStr()
          .equals(other.getErrStr())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SID_FIELD_NUMBER;
      hash = (53 * hash) + getSid();
      hash = (37 * hash) + CID_FIELD_NUMBER;
      hash = (53 * hash) + getCid();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + ERRSTR_FIELD_NUMBER;
      hash = (53 * hash) + getErrStr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kys.pb.PbGate.S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kys.pb.PbGate.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kys.pb.PbGate.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kys.pb.PbGate.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kys.pb.PbGate.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kys.pb.PbGate.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kys.pb.PbGate.S2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 服务端向客户端发送消息
     * </pre>
     *
     * Protobuf type {@code pb.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.S2C)
        com.kys.pb.PbGate.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_pb_S2C_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_pb_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kys.pb.PbGate.S2C.class, com.kys.pb.PbGate.S2C.Builder.class);
      }

      // Construct using com.kys.pb.PbGate.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        sid_ = 0;

        cid_ = 0;

        sequence_ = 0;

        code_ = 0;

        body_ = com.google.protobuf.ByteString.EMPTY;

        errStr_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_pb_S2C_descriptor;
      }

      @Override
      public com.kys.pb.PbGate.S2C getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.kys.pb.PbGate.S2C build() {
        com.kys.pb.PbGate.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.kys.pb.PbGate.S2C buildPartial() {
        com.kys.pb.PbGate.S2C result = new com.kys.pb.PbGate.S2C(this);
        result.sid_ = sid_;
        result.cid_ = cid_;
        result.sequence_ = sequence_;
        result.code_ = code_;
        result.body_ = body_;
        result.errStr_ = errStr_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kys.pb.PbGate.S2C) {
          return mergeFrom((com.kys.pb.PbGate.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kys.pb.PbGate.S2C other) {
        if (other == getDefaultInstance()) return this;
        if (other.getSid() != 0) {
          setSid(other.getSid());
        }
        if (other.getCid() != 0) {
          setCid(other.getCid());
        }
        if (other.getSequence() != 0) {
          setSequence(other.getSequence());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        if (!other.getErrStr().isEmpty()) {
          errStr_ = other.errStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kys.pb.PbGate.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kys.pb.PbGate.S2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sid_ ;
      /**
       * <pre>
       ** 服务器序列
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       */
      public int getSid() {
        return sid_;
      }
      /**
       * <pre>
       ** 服务器序列
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       */
      public Builder setSid(int value) {

        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 服务器序列
       * </pre>
       *
       * <code>int32 sid = 1;</code>
       */
      public Builder clearSid() {

        sid_ = 0;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <pre>
       ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
       * </pre>
       *
       * <code>int32 cid = 2;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <pre>
       ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
       * </pre>
       *
       * <code>int32 cid = 2;</code>
       */
      public Builder setCid(int value) {

        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 消息号（各个服独立的，跨服之间可以重复，同一个服内不可重复）
       * </pre>
       *
       * <code>int32 cid = 2;</code>
       */
      public Builder clearCid() {

        cid_ = 0;
        onChanged();
        return this;
      }

      private int sequence_ ;
      /**
       * <pre>
       ** 消息序号，用作客户端识别服务器响应
       * </pre>
       *
       * <code>int32 sequence = 3;</code>
       */
      public int getSequence() {
        return sequence_;
      }
      /**
       * <pre>
       ** 消息序号，用作客户端识别服务器响应
       * </pre>
       *
       * <code>int32 sequence = 3;</code>
       */
      public Builder setSequence(int value) {

        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 消息序号，用作客户端识别服务器响应
       * </pre>
       *
       * <code>int32 sequence = 3;</code>
       */
      public Builder clearSequence() {

        sequence_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       ** 响应结果，0是成功，1是请求超时（消息已发出），2是请求错误（消息未发出），大于100是服务器响应返回的错误
       * </pre>
       *
       * <code>int32 code = 4;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       ** 响应结果，0是成功，1是请求超时（消息已发出），2是请求错误（消息未发出），大于100是服务器响应返回的错误
       * </pre>
       *
       * <code>int32 code = 4;</code>
       */
      public Builder setCode(int value) {

        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 响应结果，0是成功，1是请求超时（消息已发出），2是请求错误（消息未发出），大于100是服务器响应返回的错误
       * </pre>
       *
       * <code>int32 code = 4;</code>
       */
      public Builder clearCode() {

        code_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       ** 消息体数据
       * </pre>
       *
       * <code>bytes body = 5;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       ** 消息体数据
       * </pre>
       *
       * <code>bytes body = 5;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 消息体数据
       * </pre>
       *
       * <code>bytes body = 5;</code>
       */
      public Builder clearBody() {

        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      private Object errStr_ = "";
      /**
       * <pre>
       ** 错误信息
       * </pre>
       *
       * <code>string errStr = 6;</code>
       */
      public String getErrStr() {
        Object ref = errStr_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errStr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       ** 错误信息
       * </pre>
       *
       * <code>string errStr = 6;</code>
       */
      public com.google.protobuf.ByteString
          getErrStrBytes() {
        Object ref = errStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 错误信息
       * </pre>
       *
       * <code>string errStr = 6;</code>
       */
      public Builder setErrStr(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        errStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 错误信息
       * </pre>
       *
       * <code>string errStr = 6;</code>
       */
      public Builder clearErrStr() {

        errStr_ = getDefaultInstance().getErrStr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 错误信息
       * </pre>
       *
       * <code>string errStr = 6;</code>
       */
      public Builder setErrStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        errStr_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.S2C)
    }

    // @@protoc_insertion_point(class_scope:pb.S2C)
    private static final com.kys.pb.PbGate.S2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kys.pb.PbGate.S2C();
    }

    public static com.kys.pb.PbGate.S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S2C>
        PARSER = new com.google.protobuf.AbstractParser<S2C>() {
      @Override
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    @Override
    public com.kys.pb.PbGate.S2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Heartbeat_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Heartbeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_KickOff_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_KickOff_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_C2S_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_C2S_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_S2C_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_S2C_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\010pb.proto\022\002pb\"(\n\tHeartbeat\022\014\n\004time\030\001 \001(" +
      "\003\022\r\n\005delay\030\002 \001(\005\"\'\n\007KickOff\022\014\n\004code\030\001 \001(" +
      "\005\022\016\n\006reason\030\002 \001(\t\"?\n\003C2S\022\013\n\003sid\030\001 \001(\005\022\013\n" +
      "\003cid\030\002 \001(\005\022\020\n\010sequence\030\003 \001(\005\022\014\n\004body\030\004 \001" +
      "(\014\"]\n\003S2C\022\013\n\003sid\030\001 \001(\005\022\013\n\003cid\030\002 \001(\005\022\020\n\010s" +
      "equence\030\003 \001(\005\022\014\n\004code\030\004 \001(\005\022\014\n\004body\030\005 \001(" +
      "\014\022\016\n\006errStr\030\006 \001(\t*v\n\013ServiceType\022\022\n\016UNKN" +
      "OW_SERVICE\020\000\022\013\n\007GATEWAY\020\001\022\014\n\010PLATFORM\020\002\022" +
      "\014\n\010LANDLORD\020\003\022\r\n\tCATCHFISH\020\004\022\014\n\010BILLIARD" +
      "\020\005\022\r\n\tELIMINATE\020\006*8\n\003MSG\022\025\n\021UNKNOWNGATEW" +
      "AYCMD\020\000\022\r\n\tHEARTBEAT\020\001\022\013\n\007KICKOFF\020\002B\024\n\nc" +
      "om.kys.pbB\006PbGateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pb_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Heartbeat_descriptor,
        new String[] { "Time", "Delay", });
    internal_static_pb_KickOff_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_KickOff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_KickOff_descriptor,
        new String[] { "Code", "Reason", });
    internal_static_pb_C2S_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_C2S_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_C2S_descriptor,
        new String[] { "Sid", "Cid", "Sequence", "Body", });
    internal_static_pb_S2C_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pb_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_S2C_descriptor,
        new String[] { "Sid", "Cid", "Sequence", "Code", "Body", "ErrStr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
