spring:
  profiles:
    active: @env@
  application:
    name: press-instrument-tools
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 50
    minIdle: 20
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
tcp:
  port: 8083
boss:
  thread:
    count: 4
worker:
  thread:
    count: 32
so:
  backlog: 1024
server:
  port: 28003
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beimi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beimi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xjgdjkys@2019
---
spring:
  profiles: product
  datasource:
    url: jdbc:mysql://172.17.16.32:3306/beimi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xjgdjkys@2019
