spring:
  profiles:
    active: @env@
  application:
    name: press-instrument-tools
tcp:
  port: 8083
boss:
  thread:
    count: 4
worker:
  thread:
    count: 32
so:
  backlog: 1024
server:
  port: 28003
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
---
spring:
  profiles: dev
---
spring:
  profiles: test
---
spring:
  profiles: product
