// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverEnum.proto

package com.kys.util.netty.proto;

public final class ServerEnum {
  private ServerEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   ** 道具变化途径 
   * </pre>
   *
   * Protobuf enum {@code com.kys.util.netty.proto.propOriginEnum}
   */
  public enum propOriginEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     ** 默认 
     * </pre>
     *
     * <code>defaultPropOrigin = 0;</code>
     */
    defaultPropOrigin(0),
    /**
     * <pre>
     ** 商城购买 
     * </pre>
     *
     * <code>shopBuy = 1;</code>
     */
    shopBuy(1),
    /**
     * <pre>
     ** 比赛取消退还玩家 
     * </pre>
     *
     * <code>cancelMatchReturn = 2;</code>
     */
    cancelMatchReturn(2),
    /**
     * <pre>
     ** 使用消耗 
     * </pre>
     *
     * <code>useExpend = 100;</code>
     */
    useExpend(100),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     ** 默认 
     * </pre>
     *
     * <code>defaultPropOrigin = 0;</code>
     */
    public static final int defaultPropOrigin_VALUE = 0;
    /**
     * <pre>
     ** 商城购买 
     * </pre>
     *
     * <code>shopBuy = 1;</code>
     */
    public static final int shopBuy_VALUE = 1;
    /**
     * <pre>
     ** 比赛取消退还玩家 
     * </pre>
     *
     * <code>cancelMatchReturn = 2;</code>
     */
    public static final int cancelMatchReturn_VALUE = 2;
    /**
     * <pre>
     ** 使用消耗 
     * </pre>
     *
     * <code>useExpend = 100;</code>
     */
    public static final int useExpend_VALUE = 100;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static propOriginEnum valueOf(int value) {
      return forNumber(value);
    }

    public static propOriginEnum forNumber(int value) {
      switch (value) {
        case 0: return defaultPropOrigin;
        case 1: return shopBuy;
        case 2: return cancelMatchReturn;
        case 100: return useExpend;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<propOriginEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        propOriginEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<propOriginEnum>() {
            public propOriginEnum findValueByNumber(int number) {
              return propOriginEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kys.util.netty.proto.ServerEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final propOriginEnum[] VALUES = values();

    public static propOriginEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private propOriginEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.kys.util.netty.proto.propOriginEnum)
  }

  /**
   * <pre>
   ** 道具id枚举 
   * </pre>
   *
   * Protobuf enum {@code com.kys.util.netty.proto.propEnum}
   */
  public enum propEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     ** 占位 
     * </pre>
     *
     * <code>defaultProp = 0;</code>
     */
    defaultProp(0),
    /**
     * <pre>
     ** 比赛场报名卡 
     * </pre>
     *
     * <code>matchApplyCard = 101;</code>
     */
    matchApplyCard(101),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     ** 占位 
     * </pre>
     *
     * <code>defaultProp = 0;</code>
     */
    public static final int defaultProp_VALUE = 0;
    /**
     * <pre>
     ** 比赛场报名卡 
     * </pre>
     *
     * <code>matchApplyCard = 101;</code>
     */
    public static final int matchApplyCard_VALUE = 101;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static propEnum valueOf(int value) {
      return forNumber(value);
    }

    public static propEnum forNumber(int value) {
      switch (value) {
        case 0: return defaultProp;
        case 101: return matchApplyCard;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<propEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        propEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<propEnum>() {
            public propEnum findValueByNumber(int number) {
              return propEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kys.util.netty.proto.ServerEnum.getDescriptor().getEnumTypes().get(1);
    }

    private static final propEnum[] VALUES = values();

    public static propEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private propEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.kys.util.netty.proto.propEnum)
  }

  /**
   * <pre>
   ** 比赛场状态 
   * </pre>
   *
   * Protobuf enum {@code com.kys.util.netty.proto.matchPlayerStatus}
   */
  public enum matchPlayerStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     ** 报名中 
     * </pre>
     *
     * <code>apply = 0;</code>
     */
    apply(0),
    /**
     * <pre>
     ** 游戏中 
     * </pre>
     *
     * <code>gaming = 1;</code>
     */
    gaming(1),
    /**
     * <pre>
     ** 小局等待 
     * </pre>
     *
     * <code>waiting = 2;</code>
     */
    waiting(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     ** 报名中 
     * </pre>
     *
     * <code>apply = 0;</code>
     */
    public static final int apply_VALUE = 0;
    /**
     * <pre>
     ** 游戏中 
     * </pre>
     *
     * <code>gaming = 1;</code>
     */
    public static final int gaming_VALUE = 1;
    /**
     * <pre>
     ** 小局等待 
     * </pre>
     *
     * <code>waiting = 2;</code>
     */
    public static final int waiting_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static matchPlayerStatus valueOf(int value) {
      return forNumber(value);
    }

    public static matchPlayerStatus forNumber(int value) {
      switch (value) {
        case 0: return apply;
        case 1: return gaming;
        case 2: return waiting;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<matchPlayerStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        matchPlayerStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<matchPlayerStatus>() {
            public matchPlayerStatus findValueByNumber(int number) {
              return matchPlayerStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kys.util.netty.proto.ServerEnum.getDescriptor().getEnumTypes().get(2);
    }

    private static final matchPlayerStatus[] VALUES = values();

    public static matchPlayerStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private matchPlayerStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.kys.util.netty.proto.matchPlayerStatus)
  }

  /**
   * <pre>
   ** 数据字典枚举 
   * </pre>
   *
   * Protobuf enum {@code com.kys.util.netty.proto.Dictionary}
   */
  public enum Dictionary
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>defaultDic = 0;</code>
     */
    defaultDic(0),
    /**
     * <pre>
     ** 支付平台appId 
     * </pre>
     *
     * <code>pay_app_id = 1;</code>
     */
    pay_app_id(1),
    /**
     * <pre>
     ** 获取订单号url 
     * </pre>
     *
     * <code>pay_get_order_url = 2;</code>
     */
    pay_get_order_url(2),
    /**
     * <pre>
     ** 查询可用支付方式url 
     * </pre>
     *
     * <code>pay_query_type = 3;</code>
     */
    pay_query_type(3),
    /**
     * <pre>
     ** 兑换红包url 
     * </pre>
     *
     * <code>pay_exchange_hb = 4;</code>
     */
    pay_exchange_hb(4),
    /**
     * <pre>
     ** 实名认证url 
     * </pre>
     *
     * <code>pay_id_verify = 5;</code>
     */
    pay_id_verify(5),
    /**
     * <pre>
     ** 支付相关所使用的密钥 
     * </pre>
     *
     * <code>pay_sercet = 6;</code>
     */
    pay_sercet(6),
    /**
     * <pre>
     ** 银联支付环境,正式服00，测试服01 
     * </pre>
     *
     * <code>pay_union_env = 7;</code>
     */
    pay_union_env(7),
    /**
     * <pre>
     ** 微信小程序支付环境，正式服0，测试环境1 
     * </pre>
     *
     * <code>pay_miniapp_env = 8;</code>
     */
    pay_miniapp_env(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>defaultDic = 0;</code>
     */
    public static final int defaultDic_VALUE = 0;
    /**
     * <pre>
     ** 支付平台appId 
     * </pre>
     *
     * <code>pay_app_id = 1;</code>
     */
    public static final int pay_app_id_VALUE = 1;
    /**
     * <pre>
     ** 获取订单号url 
     * </pre>
     *
     * <code>pay_get_order_url = 2;</code>
     */
    public static final int pay_get_order_url_VALUE = 2;
    /**
     * <pre>
     ** 查询可用支付方式url 
     * </pre>
     *
     * <code>pay_query_type = 3;</code>
     */
    public static final int pay_query_type_VALUE = 3;
    /**
     * <pre>
     ** 兑换红包url 
     * </pre>
     *
     * <code>pay_exchange_hb = 4;</code>
     */
    public static final int pay_exchange_hb_VALUE = 4;
    /**
     * <pre>
     ** 实名认证url 
     * </pre>
     *
     * <code>pay_id_verify = 5;</code>
     */
    public static final int pay_id_verify_VALUE = 5;
    /**
     * <pre>
     ** 支付相关所使用的密钥 
     * </pre>
     *
     * <code>pay_sercet = 6;</code>
     */
    public static final int pay_sercet_VALUE = 6;
    /**
     * <pre>
     ** 银联支付环境,正式服00，测试服01 
     * </pre>
     *
     * <code>pay_union_env = 7;</code>
     */
    public static final int pay_union_env_VALUE = 7;
    /**
     * <pre>
     ** 微信小程序支付环境，正式服0，测试环境1 
     * </pre>
     *
     * <code>pay_miniapp_env = 8;</code>
     */
    public static final int pay_miniapp_env_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Dictionary valueOf(int value) {
      return forNumber(value);
    }

    public static Dictionary forNumber(int value) {
      switch (value) {
        case 0: return defaultDic;
        case 1: return pay_app_id;
        case 2: return pay_get_order_url;
        case 3: return pay_query_type;
        case 4: return pay_exchange_hb;
        case 5: return pay_id_verify;
        case 6: return pay_sercet;
        case 7: return pay_union_env;
        case 8: return pay_miniapp_env;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Dictionary>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Dictionary> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Dictionary>() {
            public Dictionary findValueByNumber(int number) {
              return Dictionary.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kys.util.netty.proto.ServerEnum.getDescriptor().getEnumTypes().get(3);
    }

    private static final Dictionary[] VALUES = values();

    public static Dictionary valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Dictionary(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.kys.util.netty.proto.Dictionary)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020serverEnum.proto\022\030com.kys.util.netty.p" +
      "roto*Z\n\016propOriginEnum\022\025\n\021defaultPropOri" +
      "gin\020\000\022\013\n\007shopBuy\020\001\022\025\n\021cancelMatchReturn\020" +
      "\002\022\r\n\tuseExpend\020d*/\n\010propEnum\022\017\n\013defaultP" +
      "rop\020\000\022\022\n\016matchApplyCard\020e*7\n\021matchPlayer" +
      "Status\022\t\n\005apply\020\000\022\n\n\006gaming\020\001\022\013\n\007waiting" +
      "\020\002*\267\001\n\nDictionary\022\016\n\ndefaultDic\020\000\022\016\n\npay" +
      "_app_id\020\001\022\025\n\021pay_get_order_url\020\002\022\022\n\016pay_" +
      "query_type\020\003\022\023\n\017pay_exchange_hb\020\004\022\021\n\rpay" +
      "_id_verify\020\005\022\016\n\npay_sercet\020\006\022\021\n\rpay_unio",
      "n_env\020\007\022\023\n\017pay_miniapp_env\020\010b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
